export let ticketdata: Object[] = [
    {
        "TicketID": "65823",
        "TypeofRequest": "Bug",
        "Category": "Support",
        "Title": "Login Failure Report",
        "Assignee": "Sarah Lee",
        "Status": "Open",
        "Priority": "Low",
        "CreatedDate": new Date('2026-08-25'),
        "DueDate": new Date('2026-08-26'),
    },
    {
        "TicketID": "65822",
        "TypeofRequest": "Technical Support",
        "Category": "Product",
        "Title": "Login Setup Assistance",
        "Assignee": "Tom Wilson",
        "Status": "Open",
        "Priority": "Low",
        "CreatedDate": new Date('2026-08-24'),
        "DueDate": new Date('2026-08-25'),
    },
    {
        "TicketID": "65821",
        "TypeofRequest": "Feature Enhancement",
        "Category": "Support",
        "Title": "Dashboard Enhancement Request",
        "Assignee": "Alex Brown",
        "Status": "In Progress",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-08-23'),
        "DueDate": new Date('2026-09-01'),
    },
    {
        "TicketID": "65820",
        "TypeofRequest": "Refund",
        "Category": "Support",
        "Title": "Order Refund Request",
        "Assignee": "Priya Kumar",
        "Status": "Validated",
        "Priority": "Low",
        "CreatedDate": new Date('2026-08-22'),
        "DueDate": new Date('2026-08-23'),
    },
    {
        "TicketID": "65819",
        "TypeofRequest": "Refund",
        "Category": "Product",
        "Title": "Payment Refund Status Inquiry",
        "Assignee": "Mike Johnson",
        "Status": "Open",
        "Priority": "Medium",
        "CreatedDate": new Date('2026-08-21'),
        "DueDate": new Date('2026-08-23'),
    },
    {
        "TicketID": "65818",
        "TypeofRequest": "Bug",
        "Category": "Product",
        "Title": "Checkout Error Investigation",
        "Assignee": "Sarah Lee",
        "Status": "Validated",
        "Priority": "Low",
        "CreatedDate": new Date('2026-08-20'),
        "DueDate": new Date('2026-08-21'),
    },
    {
        "TicketID": "65817",
        "TypeofRequest": "Bug",
        "Category": "Billing",
        "Title": "Search Defect Needs Fixing",
        "Assignee": "Jane Smith",
        "Status": "In Progress",
        "Priority": "Medium",
        "CreatedDate": new Date('2026-08-19'),
        "DueDate": new Date('2026-08-21'),
    },
    {
        "TicketID": "65816",
        "TypeofRequest": "Feature Enhancement",
        "Category": "Product",
        "Title": "Search Improvement Proposal",
        "Assignee": "Mike Johnson",
        "Status": "Open",
        "Priority": "Medium",
        "CreatedDate": new Date('2026-08-18'),
        "DueDate": new Date('2026-08-23'),
    },
    {
        "TicketID": "65815",
        "TypeofRequest": "Refund",
        "Category": "Support",
        "Title": "Invoice Refund Review Request",
        "Assignee": "Tom Wilson",
        "Status": "Done",
        "Priority": "Medium",
        "CreatedDate": new Date('2026-08-17'),
        "DueDate": new Date('2026-08-18'),
    },
    {
        "TicketID": "65814",
        "TypeofRequest": "Refund",
        "Category": "Product",
        "Title": "Purchase Refund Request",
        "Assignee": "Alex Brown",
        "Status": "Done",
        "Priority": "Medium",
        "CreatedDate": new Date('2026-08-16'),
        "DueDate": new Date('2026-08-18'),
    },
    {
        "TicketID": "65813",
        "TypeofRequest": "Feature Enhancement",
        "Category": "Product",
        "Title": "Reports Feature Upgrade Request",
        "Assignee": "Alex Brown",
        "Status": "Validated",
        "Priority": "Low",
        "CreatedDate": new Date('2026-08-15'),
        "DueDate": new Date('2026-09-03'),
    },
    {
        "TicketID": "65812",
        "TypeofRequest": "Refund",
        "Category": "Support",
        "Title": "Charge Refund Status Inquiry",
        "Assignee": "Priya Kumar",
        "Status": "In Progress",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-08-14'),
        "DueDate": new Date('2026-08-16'),
    },
    {
        "TicketID": "65811",
        "TypeofRequest": "Feature Enhancement",
        "Category": "Billing",
        "Title": "Filters Enhancement Request",
        "Assignee": "Priya Kumar",
        "Status": "Done",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-08-13'),
        "DueDate": new Date('2026-08-31'),
    },
    {
        "TicketID": "65810",
        "TypeofRequest": "Technical Support",
        "Category": "Product",
        "Title": "Password Support Guidance",
        "Assignee": "Sarah Lee",
        "Status": "Done",
        "Priority": "Low",
        "CreatedDate": new Date('2026-08-12'),
        "DueDate": new Date('2026-08-13'),
    },
    {
        "TicketID": "65809",
        "TypeofRequest": "Feature Enhancement",
        "Category": "Support",
        "Title": "Export Improvement Proposal",
        "Assignee": "John Doe",
        "Status": "Validated",
        "Priority": "Low",
        "CreatedDate": new Date('2026-08-11'),
        "DueDate": new Date('2026-08-26'),
    },
    {
        "TicketID": "65808",
        "TypeofRequest": "Bug",
        "Category": "Support",
        "Title": "Dashboard Failure Report",
        "Assignee": "Emily Davis",
        "Status": "Done",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-08-10'),
        "DueDate": new Date('2026-08-11'),
    },
    {
        "TicketID": "65807",
        "TypeofRequest": "Bug",
        "Category": "Product",
        "Title": "Upload Error Investigation",
        "Assignee": "Alex Brown",
        "Status": "Done",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-08-09'),
        "DueDate": new Date('2026-08-12'),
    },
    {
        "TicketID": "65806",
        "TypeofRequest": "Refund",
        "Category": "Support",
        "Title": "Transaction Refund Review Request",
        "Assignee": "Alex Brown",
        "Status": "Done",
        "Priority": "High",
        "CreatedDate": new Date('2026-08-08'),
        "DueDate": new Date('2026-08-10'),
    },
    {
        "TicketID": "65805",
        "TypeofRequest": "Bug",
        "Category": "Billing",
        "Title": "Billing Defect Needs Fixing",
        "Assignee": "Alex Brown",
        "Status": "Open",
        "Priority": "High",
        "CreatedDate": new Date('2026-08-07'),
        "DueDate": new Date('2026-08-11'),
    },
    {
        "TicketID": "65804",
        "TypeofRequest": "Refund",
        "Category": "Product",
        "Title": "Billing Refund Request",
        "Assignee": "Mike Johnson",
        "Status": "Done",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-08-06'),
        "DueDate": new Date('2026-08-07'),
    },
    {
        "TicketID": "65803",
        "TypeofRequest": "Bug",
        "Category": "Product",
        "Title": "Profile Failure Report",
        "Assignee": "Tom Wilson",
        "Status": "Open",
        "Priority": "High",
        "CreatedDate": new Date('2026-08-05'),
        "DueDate": new Date('2026-08-08'),
    },
    {
        "TicketID": "65802",
        "TypeofRequest": "Refund",
        "Category": "Product",
        "Title": "Credit Refund Status Inquiry",
        "Assignee": "John Doe",
        "Status": "Done",
        "Priority": "High",
        "CreatedDate": new Date('2026-08-04'),
        "DueDate": new Date('2026-08-06'),
    },
    {
        "TicketID": "65801",
        "TypeofRequest": "Refund",
        "Category": "Product",
        "Title": "Receipt Refund Review Request",
        "Assignee": "Alex Brown",
        "Status": "In Progress",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-08-03'),
        "DueDate": new Date('2026-08-04'),
    },
    {
        "TicketID": "65800",
        "TypeofRequest": "Bug",
        "Category": "Product",
        "Title": "Notifications Error Investigation",
        "Assignee": "Alex Brown",
        "Status": "Validated",
        "Priority": "Low",
        "CreatedDate": new Date('2026-08-02'),
        "DueDate": new Date('2026-08-04'),
    },
    {
        "TicketID": "65799",
        "TypeofRequest": "Technical Support",
        "Category": "Billing",
        "Title": "Upload Troubleshooting Help",
        "Assignee": "Jane Smith",
        "Status": "In Progress",
        "Priority": "Medium",
        "CreatedDate": new Date('2026-08-01'),
        "DueDate": new Date('2026-08-02'),
    },
    {
        "TicketID": "65798",
        "TypeofRequest": "Feature Enhancement",
        "Category": "Product",
        "Title": "Notifications Feature Upgrade Request",
        "Assignee": "Jane Smith",
        "Status": "Open",
        "Priority": "Medium",
        "CreatedDate": new Date('2026-07-31'),
        "DueDate": new Date('2026-08-08'),
    },
    {
        "TicketID": "65797",
        "TypeofRequest": "Subscription Cancellation",
        "Category": "Support",
        "Title": "Subscription Cancellation Request",
        "Assignee": "Alex Brown",
        "Status": "Done",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-07-30'),
        "DueDate": new Date('2026-08-01'),
    },
    {
        "TicketID": "65796",
        "TypeofRequest": "Technical Support",
        "Category": "Product",
        "Title": "Dashboard Setup Assistance",
        "Assignee": "Tom Wilson",
        "Status": "In Progress",
        "Priority": "High",
        "CreatedDate": new Date('2026-07-29'),
        "DueDate": new Date('2026-07-30'),
    },
    {
        "TicketID": "65795",
        "TypeofRequest": "Technical Support",
        "Category": "Product",
        "Title": "Reports Support Guidance",
        "Assignee": "Priya Kumar",
        "Status": "In Progress",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-07-28'),
        "DueDate": new Date('2026-07-30'),
    },
    {
        "TicketID": "65794",
        "TypeofRequest": "Technical Support",
        "Category": "Support",
        "Title": "Calendar Troubleshooting Help",
        "Assignee": "Sarah Lee",
        "Status": "Done",
        "Priority": "Low",
        "CreatedDate": new Date('2026-07-27'),
        "DueDate": new Date('2026-07-28'),
    },
    {
        "TicketID": "65793",
        "TypeofRequest": "Refund",
        "Category": "Billing",
        "Title": "Checkout Refund Request",
        "Assignee": "Alex Brown",
        "Status": "Done",
        "Priority": "High",
        "CreatedDate": new Date('2026-07-26'),
        "DueDate": new Date('2026-07-29'),
    },
    {
        "TicketID": "65792",
        "TypeofRequest": "Feature Enhancement",
        "Category": "Product",
        "Title": "Calendar Enhancement Request",
        "Assignee": "Emily Davis",
        "Status": "In Progress",
        "Priority": "Low",
        "CreatedDate": new Date('2026-07-25'),
        "DueDate": new Date('2026-08-06'),
    },
    {
        "TicketID": "65791",
        "TypeofRequest": "Feature Enhancement",
        "Category": "Support",
        "Title": "Profile Improvement Proposal",
        "Assignee": "John Doe",
        "Status": "Done",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-07-24'),
        "DueDate": new Date('2026-08-12'),
    },
    {
        "TicketID": "65790",
        "TypeofRequest": "Technical Support",
        "Category": "Billing",
        "Title": "Invoice Setup Assistance",
        "Assignee": "Mike Johnson",
        "Status": "Validated",
        "Priority": "High",
        "CreatedDate": new Date('2026-07-23'),
        "DueDate": new Date('2026-07-24'),
    },
    {
        "TicketID": "65789",
        "TypeofRequest": "Technical Support",
        "Category": "Product",
        "Title": "Profile Support Guidance",
        "Assignee": "John Doe",
        "Status": "In Progress",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-07-22'),
        "DueDate": new Date('2026-07-23'),
    },
    {
        "TicketID": "65788",
        "TypeofRequest": "Bug",
        "Category": "Product",
        "Title": "Reports Defect Needs Fixing",
        "Assignee": "Emily Davis",
        "Status": "Done",
        "Priority": "Low",
        "CreatedDate": new Date('2026-07-21'),
        "DueDate": new Date('2026-07-24'),
    },
    {
        "TicketID": "65787",
        "TypeofRequest": "Subscription Cancellation",
        "Category": "Billing",
        "Title": "Membership Cancellation Assistance",
        "Assignee": "Jane Smith",
        "Status": "In Progress",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-07-20'),
        "DueDate": new Date('2026-07-22'),
    },
    {
        "TicketID": "65786",
        "TypeofRequest": "Feature Enhancement",
        "Category": "Product",
        "Title": "Checkout Feature Upgrade Request",
        "Assignee": "Alex Brown",
        "Status": "In Progress",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-07-19'),
        "DueDate": new Date('2026-08-03'),
    },
    {
        "TicketID": "65785",
        "TypeofRequest": "Subscription Cancellation",
        "Category": "Product",
        "Title": "Plan Cancellation Confirmation",
        "Assignee": "John Doe",
        "Status": "Done",
        "Priority": "Low",
        "CreatedDate": new Date('2026-07-18'),
        "DueDate": new Date('2026-07-20'),
    },
    {
        "TicketID": "65784",
        "TypeofRequest": "Subscription Cancellation",
        "Category": "Support",
        "Title": "Renewal Cancellation Request",
        "Assignee": "Sarah Lee",
        "Status": "Done",
        "Priority": "Medium",
        "CreatedDate": new Date('2026-07-17'),
        "DueDate": new Date('2026-07-18'),
    },
    {
        "TicketID": "65783",
        "TypeofRequest": "Technical Support",
        "Category": "Product",
        "Title": "Address Troubleshooting Help",
        "Assignee": "Emily Davis",
        "Status": "In Progress",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-07-16'),
        "DueDate": new Date('2026-07-17'),
    },
    {
        "TicketID": "65782",
        "TypeofRequest": "Refund",
        "Category": "Support",
        "Title": "Delivery Refund Status Inquiry",
        "Assignee": "Mike Johnson",
        "Status": "In Progress",
        "Priority": "High",
        "CreatedDate": new Date('2026-07-15'),
        "DueDate": new Date('2026-07-18'),
    },
    {
        "TicketID": "65781",
        "TypeofRequest": "Technical Support",
        "Category": "Billing",
        "Title": "Payment Setup Assistance",
        "Assignee": "Mike Johnson",
        "Status": "Done",
        "Priority": "High",
        "CreatedDate": new Date('2026-07-14'),
        "DueDate": new Date('2026-07-16'),
    },
    {
        "TicketID": "65780",
        "TypeofRequest": "Refund",
        "Category": "Product",
        "Title": "Return Refund Review Request",
        "Assignee": "Jane Smith",
        "Status": "Done",
        "Priority": "Low",
        "CreatedDate": new Date('2026-07-13'),
        "DueDate": new Date('2026-07-15'),
    },
    {
        "TicketID": "65779",
        "TypeofRequest": "Technical Support",
        "Category": "Support",
        "Title": "Orders Support Guidance",
        "Assignee": "Tom Wilson",
        "Status": "In Progress",
        "Priority": "High",
        "CreatedDate": new Date('2026-07-12'),
        "DueDate": new Date('2026-07-13'),
    },
    {
        "TicketID": "65778",
        "TypeofRequest": "Feature Enhancement",
        "Category": "Support",
        "Title": "Analytics Enhancement Request",
        "Assignee": "Tom Wilson",
        "Status": "Done",
        "Priority": "High",
        "CreatedDate": new Date('2026-07-11'),
        "DueDate": new Date('2026-07-31'),
    },
    {
        "TicketID": "65777",
        "TypeofRequest": "Bug",
        "Category": "Product",
        "Title": "Calendar Failure Report",
        "Assignee": "Priya Kumar",
        "Status": "Open",
        "Priority": "Low",
        "CreatedDate": new Date('2026-07-10'),
        "DueDate": new Date('2026-07-11'),
    },
    {
        "TicketID": "65776",
        "TypeofRequest": "Bug",
        "Category": "Product",
        "Title": "Invoice Error Investigation",
        "Assignee": "John Doe",
        "Status": "In Progress",
        "Priority": "Urgent",
        "CreatedDate": new Date('2026-07-09'),
        "DueDate": new Date('2026-07-11'),
    },
    {
        "TicketID": "65775",
        "TypeofRequest": "Subscription Cancellation",
        "Category": "Support",
        "Title": "Account Cancellation Assistance",
        "Assignee": "Tom Wilson",
        "Status": "In Progress",
        "Priority": "Medium",
        "CreatedDate": new Date('2026-07-08'),
        "DueDate": new Date('2026-07-09'),
    },
    {
        "TicketID": "65774",
        "TypeofRequest": "Subscription Cancellation",
        "Category": "Product",
        "Title": "Service Cancellation Confirmation",
        "Assignee": "John Doe",
        "Status": "Open",
        "Priority": "High",
        "CreatedDate": new Date('2026-07-07'),
        "DueDate": new Date('2026-07-09'),
    }];