export let shiftPlanData: Object[] = [
{
    Name: 'Dr. Sarah Johnson',
    Designation: 'Chief Surgeon',
    Time9AM: 'Weekly Meeting',
    Time10AM: 'Major Surgery',
    Time11AM: 'Major Surgery',
    Time12PM: 'Cardiac Operation',
    Time1PM: 'Cardiac Operation',
    Time2PM: 'Cardiac Operation',
    Time3PM: 'Post-up Consultaion',
    Time4PM: 'Post-up Consultaion',
    Time5PM: 'Emergency Coverage',
    Time6PM: 'Emergency Coverage',
    Time7PM: 'Emergency Coverage',
},
{
    Name: 'Dr. Michael Chen',
    Designation: 'Cardiologist',
    Time9AM: 'Cardiologist Ward Rounds',
    Time10AM: 'Cardiologist Emergency Ward',
    Time11AM: 'Cardiologist Emergency Ward',
    Time12PM: 'Cardialogist Research',
    Time1PM: 'Cardiologist General Checkup',
    Time2PM: 'Cardiologist General Checkup',
    Time3PM: 'Cardiologist General Checkup',
    Time4PM: 'Cardiologist General Checkup',
    Time5PM: 'Cardiologist Lab Work',
    Time6PM: 'Cardiologist Consultation',
    Time7PM: 'Cardiologist Surgery',
},
{
    Name: 'Dr. Emily Rodriguez',
    Designation: 'Pediatrician',
    Time9AM: 'Pediatrician Casualty',
    Time10AM: 'Pediatrician Casualty',
    Time11AM: 'Pediatrician Training',
    Time12PM: 'Pediatrician Research',
    Time1PM: 'Pediatrician Surgery',
    Time2PM: 'Pediatrician Surgery',
    Time3PM: 'Pediatrician Surgery',
    Time4PM: 'Pediatrician General Checkup',
    Time5PM: 'Pediatrician Consultation',
    Time6PM: 'Pediatrician Consultation',
    Time7PM: 'Pediatrician Ward Rounds',
},
{
    Name: 'Dr. David Wilson',
    Designation: 'Orthopedic Surgeon',
    Time9AM: 'Orthopedic Surgeon Research',
    Time10AM: 'Orthopedic Surgeon Ward Rounds',
    Time11AM: 'Orthopedic Surgeon Ward Rounds',
    Time12PM: 'Orthopedic Surgeon Training',
    Time1PM: 'Orthopedic Surgeon Surgery',
    Time2PM: 'Orthopedic Surgeon Consultation',
    Time3PM: 'Orthopedic Surgeon Consultation',
    Time4PM: 'Orthopedic Surgeon Consultation',
    Time5PM: 'Orthopedic Surgeon Casualty',
    Time6PM: 'Orthopedic Surgeon Casualty',
    Time7PM: 'Orthopedic Surgeon Operation Theatre',
},
{
    Name: 'Dr. Lisa Thompson',
    Designation: 'Neurologist',
    Time9AM: 'Week Off',
    Time10AM: 'Week Off',
    Time11AM: 'Week Off',
    Time12PM: 'Week Off',
    Time1PM: 'Week Off',
    Time2PM: 'Week Off',
    Time3PM: 'Week Off',
    Time4PM: 'Week Off',
    Time5PM: 'Week Off',
    Time6PM: 'Week Off',
    Time7PM: 'Week Off',
},
{
    Name: 'Dr. James Anderson',
    Designation: 'General Physician',
    Time9AM: 'General Physician Lab Work',
    Time10AM: 'General Physician General Checkup',
    Time11AM: 'General Physician General Checkup',
    Time12PM: 'General Physician Consultation',
    Time1PM: 'General Physician Consultation',
    Time2PM: 'General Physician Consultation',
    Time3PM: 'General Physician Ward Rounds',
    Time4PM: 'General Physician Casualty',
    Time5PM: 'General Physician Training',
    Time6PM: 'General Physician Training',
    Time7PM: 'General Physician Research',
},
{
    Name: 'Dr. Maria Garcia',
    Designation: 'Gynecologist',
    Time9AM: 'Gynecologist Consultation',
    Time10AM: 'Gynecologist Operation Theatre',
    Time11AM: 'Gynecologist Operation Theatre',
    Time12PM: 'Gynecologist Ward Rounds',
    Time1PM: 'Gynecologist Surgery',
    Time2PM: 'Gynecologist Surgery',
    Time3PM: 'Gynecologist Surgery',
    Time4PM: 'Gynecologist Research',
    Time5PM: 'Gynecologist General Checkup',
    Time6PM: 'Gynecologist General Checkup',
    Time7PM: 'Gynecologist Training',
},
{
    Name: 'Dr. Robert Kim',
    Designation: 'Emergency Medicine Doctor',
    Time9AM: 'Emergency Medicine Doctor Casualty',
    Time10AM: 'Emergency Medicine Doctor Casualty',
    Time11AM: 'Emergency Medicine Doctor Consultation',
    Time12PM: 'Emergency Medicine Doctor Training',
    Time1PM: 'Emergency Medicine Doctor Ward Rounds',
    Time2PM: 'Emergency Medicine Doctor Ward Rounds',
    Time3PM: 'Emergency Medicine Doctor Ward Rounds',
    Time4PM: 'Emergency Medicine Doctor Surgery',
    Time5PM: 'Emergency Medicine Doctor Research',
    Time6PM: 'Emergency Medicine Doctor Research',
    Time7PM: 'Emergency Medicine Doctor Emergency Ward',
},
{
    Name: 'Dr. Jennifer Lee',
    Designation: 'Psychiatrist',
    Time9AM: 'Psychiatrist Research',
    Time10AM: 'Psychiatrist Training',
    Time11AM: 'Psychiatrist General Checkup',
    Time12PM: 'Psychiatrist General Checkup',
    Time1PM: 'Psychiatrist General Checkup',
    Time2PM: 'Psychiatrist General Checkup',
    Time3PM: 'Psychiatrist Lab Work',
    Time4PM: 'Psychiatrist Casualty',
    Time5PM: 'Psychiatrist Casualty',
    Time6PM: 'Psychiatrist Consultation',
    Time7PM: 'Psychiatrist Ward Rounds',
},
{
    Name: 'Dr. Thomas Brown',
    Designation: 'Radiologist',
    Time9AM: 'Radiologist Training',
    Time10AM: 'Radiologist Training',
    Time11AM: 'Radiologist Emergency Ward',
    Time12PM: 'Radiologist General Checkup',
    Time1PM: 'Radiologist General Checkup',
    Time2PM: 'Radiologist General Checkup',
    Time3PM: 'Radiologist Ward Rounds',
    Time4PM: 'Radiologist Lab Work',
    Time5PM: 'Radiologist Consultation',
    Time6PM: 'Radiologist Consultation',
    Time7PM: 'Radiologist Research',
},
];