export var inventoryData = [
    {
      Inventor: 'Kia Silverbrook',
      NumberofPatentFamilies: 4737,
      Country: 'Australia',
      'Number of INPADOC patents': 9839,
      Active: '1994-2016',
      Mainfieldsofinvention:
        'Printing, Digital paper, Internet, Electronics,Lab-on-a-chip, MEMS, Mechanical, VLSI',
    },
    {
      Inventor: 'Shunpei Yamazaki',
      NumberofPatentFamilies: 4677,
      Country: 'Japan',
      'Number of INPADOC patents': 10000,
      Active: '1976-2016',
      Mainfieldsofinvention:
        'Thin film transistors, Liquid crystal displays, Solar cells, Flash memory, OLED',
    },
    {
      Inventor: 'Lowell L. Wood, Jr.',
      NumberofPatentFamilies: 1419,
      Country: 'USA',
      'Number of INPADOC patents': 1332,
      Active: '1977-2016',
      Mainfieldsofinvention: 'Mosquito laser, Nuclear weapons',
    },
    {
      Inventor: 'Paul Lapstun',
      NumberofPatentFamilies: 1281,
      Country: 'Australia',
      'Number of INPADOC patents': 3099,
      Active: '2000-2016',
      Mainfieldsofinvention:
        'Printing, Digital paper, Internet, Electronics, CGI, VLSI',
    },
    {
      Inventor: 'Gurtej Sandhu',
      NumberofPatentFamilies: 1255,
      Country: 'India',
      'Number of INPADOC patents': 2038,
      Active: '1991-2016',
      Mainfieldsofinvention:
        'Thin film processes and materials, VLSI, Semiconductor device fabrication',
    },
    {
      Inventor: 'Jun Koyama',
      NumberofPatentFamilies: 1240,
      Country: 'Japan',
      'Number of INPADOC patents': 4126,
      Active: '1991-2016',
      Mainfieldsofinvention:
        'Thin film transistors, Liquid crystal displays, OLED',
    },
    {
      Inventor: 'Roderick A. Hyde',
      NumberofPatentFamilies: 1240,
      Country: 'USA',
      'Number of INPADOC patents': 3360,
      Active: '2001-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Leonard Forbes',
      NumberofPatentFamilies: 1093,
      Country: 'Canada',
      'Number of INPADOC patents': 1398,
      Active: '1991-2016',
      Mainfieldsofinvention:
        'Semiconductor Memories, CCDs, Thin film processes and materials, VLSI',
    },
    {
      Inventor: 'Thomas Edison',
      NumberofPatentFamilies: 1084,
      Country: 'USA',
      'Number of INPADOC patents': 2332,
      Active: '1847(b)-1931(d)',
      Mainfieldsofinvention:
        'Electric power, Lighting, Batteries, Phonograph, Cement, Telegraphy, Mining',
    },
    {
      Inventor: 'Donald E. Weder',
      NumberofPatentFamilies: 999,
      Country: 'USA',
      'Number of INPADOC patents': 1993,
      Active: '1976-2015',
      Mainfieldsofinvention: 'Florist supplies',
    },
    {
      Inventor: 'George Albert Lyon',
      NumberofPatentFamilies: 993,
      Country: 'Canada',
      'Number of INPADOC patents': 0,
      Active: '1882(b)-1961(d)',
      Mainfieldsofinvention: 'Automotive, Stainless steel products',
    },
    {
      Inventor: "John F. O'Connor",
      NumberofPatentFamilies: 949,
      Country: 'USA',
      'Number of INPADOC patents': 0,
      Active: '1864(b)-1938(d)',
      Mainfieldsofinvention: 'Railway draft gearing',
    },
    {
      Inventor: 'Melvin De Groote',
      NumberofPatentFamilies: 925,
      Country: 'USA',
      'Number of INPADOC patents': 0,
      Active: '1895(b)-1963(d)',
      Mainfieldsofinvention: 'Chemical de-emulsifiers',
    },
    {
      Inventor: 'Jay S. Walker',
      NumberofPatentFamilies: 918,
      Country: 'USA',
      'Number of INPADOC patents': 2206,
      Active: '1998-2016',
      Mainfieldsofinvention: 'Gaming machines',
    },
    {
      Inventor: 'Edward K. Y. Jung',
      NumberofPatentFamilies: 911,
      Country: 'USA',
      'Number of INPADOC patents': 2254,
      Active: '1996-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Francis H. Richards',
      NumberofPatentFamilies: 894,
      Country: 'USA',
      'Number of INPADOC patents': 12,
      Active: '1850(b)-19??(d)',
      Mainfieldsofinvention: 'Mechanical, automation',
    },
    {
      Inventor: 'Kangguo Cheng',
      NumberofPatentFamilies: 884,
      Country: 'USA',
      'Number of INPADOC patents': 1314,
      Active: '2004-2016',
      Mainfieldsofinvention:
        'Semiconductor device fabrication, Semiconductor memory, Semiconductor device',
    },
    {
      Inventor: 'Clarence T. Tegreene',
      NumberofPatentFamilies: 872,
      Country: 'USA',
      'Number of INPADOC patents': 2255,
      Active: '2000-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Ahmadreza Rofougaran',
      NumberofPatentFamilies: 808,
      Country: 'USA',
      'Number of INPADOC patents': 1396,
      Active: '2002-2016',
      Mainfieldsofinvention: 'Radio Frequency Integrated Circuits',
    },
    {
      Inventor: 'Shou-Shan Fan',
      NumberofPatentFamilies: 805,
      Country: 'China',
      'Number of INPADOC patents': 2120,
      Active: '2006-2016',
      Mainfieldsofinvention:
        'Carbon nanotubes and applications of carbon nanotubes',
    },
    {
      Inventor: 'Michael J. Sullivan',
      NumberofPatentFamilies: 788,
      Country: 'USA',
      'Number of INPADOC patents': 1560,
      Active: '1977-2016',
      Mainfieldsofinvention: 'Golf balls',
    },
    {
      Inventor: 'Rick Allen Hamilton II',
      NumberofPatentFamilies: 773,
      Country: 'USA',
      'Number of INPADOC patents': 1064,
      Active: '1999-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Warren Farnworth',
      NumberofPatentFamilies: 770,
      Country: 'USA',
      'Number of INPADOC patents': 931,
      Active: '1990-2016',
      Mainfieldsofinvention: 'Semiconductor packaging',
    },
    {
      Inventor: 'Carleton Ellis',
      NumberofPatentFamilies: 753,
      Country: 'USA',
      'Number of INPADOC patents': 21,
      Active: '1876(b)-1941(d)',
      Mainfieldsofinvention:
        'Margarine, Polyester, Anti-knock gasoline, Paint stripper',
    },
    {
      Inventor: 'William H. Eby',
      NumberofPatentFamilies: 733,
      Country: 'USA',
      'Number of INPADOC patents': 758,
      Active: '1994-2016',
      Mainfieldsofinvention: 'Transgenic soybeans',
    },
    {
      Inventor: 'Hideo Ando',
      NumberofPatentFamilies: 728,
      Country: 'Japan',
      'Number of INPADOC patents': 2588,
      Active: '1983-2016',
      Mainfieldsofinvention: 'Optical recording',
    },
    {
      Inventor: 'Salman Akram',
      NumberofPatentFamilies: 728,
      Country: 'USA',
      'Number of INPADOC patents': 915,
      Active: '1995-2016',
      Mainfieldsofinvention: 'Semiconductor packaging',
    },
    {
      Inventor: 'George Spector',
      NumberofPatentFamilies: 722,
      Country: 'USA',
      'Number of INPADOC patents': 747,
      Active: '1976-1998',
      Mainfieldsofinvention: 'Gadgets, Toys',
    },
    {
      Inventor: 'Jeyhan Karaoguz',
      NumberofPatentFamilies: 721,
      Country: 'USA',
      'Number of INPADOC patents': 1530,
      Active: '1996-2016',
      Mainfieldsofinvention: 'Wireless communications, Computer networks',
    },
    {
      Inventor: 'Elihu Thomson',
      NumberofPatentFamilies: 696,
      Country: 'UK',
      'Number of INPADOC patents': 50,
      Active: '1853(b)-1937(d)',
      Mainfieldsofinvention:
        'Electric power, Arc lamp, Electric motors, Lightning arrester, Arc welder',
    },
    {
      Inventor: 'Austin L. Gurney',
      NumberofPatentFamilies: 695,
      Country: 'USA',
      'Number of INPADOC patents': 3909,
      Active: '1999-2016',
      Mainfieldsofinvention: 'Proteins, Antibodies',
    },
    {
      Inventor: 'Tetsujiro Kondo',
      NumberofPatentFamilies: 684,
      Country: 'Japan',
      'Number of INPADOC patents': 4158,
      Active: '1987-2015',
      Mainfieldsofinvention: 'Signal processing, Image processing',
    },
    {
      Inventor: 'Nathan Myhrvold',
      NumberofPatentFamilies: 661,
      Country: 'USA',
      'Number of INPADOC patents': 1690,
      Active: '1994-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'William I. Wood',
      NumberofPatentFamilies: 653,
      Country: 'USA',
      'Number of INPADOC patents': 3560,
      Active: '1981-2016',
      Mainfieldsofinvention: 'Proteins, Antibodies',
    },
    {
      Inventor: 'Simon R. Walmsley',
      NumberofPatentFamilies: 651,
      Country: 'Australia',
      'Number of INPADOC patents': 1249,
      Active: '1995-2015',
      Mainfieldsofinvention: 'Printing, Electronics, VLSI, Cryptography',
    },
    {
      Inventor: 'Mark Malamud',
      NumberofPatentFamilies: 632,
      Country: 'USA',
      'Number of INPADOC patents': 1759,
      Active: '1997-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Royce A. Levien',
      NumberofPatentFamilies: 630,
      Country: 'USA',
      'Number of INPADOC patents': 1799,
      Active: '1997-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Audrey D. Goddard',
      NumberofPatentFamilies: 622,
      Country: 'USA',
      'Number of INPADOC patents': 3416,
      Active: '1997-2014',
      Mainfieldsofinvention: 'Proteins, Antibodies',
    },
    {
      Inventor: 'Muriel Y. Ishikawa',
      NumberofPatentFamilies: 619,
      Country: 'USA',
      'Number of INPADOC patents': 1660,
      Active: '2002-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Robert W. Lord',
      NumberofPatentFamilies: 618,
      Country: 'USA',
      'Number of INPADOC patents': 1708,
      Active: '2003-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Jerome Lemelson',
      NumberofPatentFamilies: 606,
      Country: 'USA',
      'Number of INPADOC patents': 60,
      Active: '1923(b)-1997(d)',
      Mainfieldsofinvention:
        'Toys, Industrial robots, Cordless telephones, Fax machines, Videocassette recorders',
    },
    {
      Inventor: 'Béla Barényi',
      NumberofPatentFamilies: 595,
      Country: 'Austria',
      'Number of INPADOC patents': 1244,
      Active: '1907(b)-1997(d)',
      Mainfieldsofinvention: 'Passive safety in automobiles',
    },
    {
      Inventor: 'Kie Y Ahn',
      NumberofPatentFamilies: 593,
      Country: 'USA',
      'Number of INPADOC patents': 709,
      Active: '1976-2016',
      Mainfieldsofinvention:
        'Thin film processes and materials, VLSI, Semiconductor device fabrication',
    },
    {
      Inventor: 'Tadahiro Ohmi',
      NumberofPatentFamilies: 592,
      Country: 'Japan',
      'Number of INPADOC patents': 2691,
      Active: '1981-2016',
      Mainfieldsofinvention:
        'Thin film processes and materials, Semiconductor device fabrication',
    },
    {
      Inventor: 'Jordin T. Kare',
      NumberofPatentFamilies: 585,
      Country: 'USA',
      'Number of INPADOC patents': 1559,
      Active: '1992-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Paul J. Godowski',
      NumberofPatentFamilies: 579,
      Country: 'USA',
      'Number of INPADOC patents': 2605,
      Active: '1994-2014',
      Mainfieldsofinvention: 'Proteins, Antibodies',
    },
    {
      Inventor: 'Artur Fischer',
      NumberofPatentFamilies: 570,
      Country: 'Germany',
      'Number of INPADOC patents': 3097,
      Active: '1976-2002',
      Mainfieldsofinvention: 'Fasteners, Construction toys',
    },
    {
      Inventor: 'Edward J. Nowak',
      NumberofPatentFamilies: 564,
      Country: 'USA',
      'Number of INPADOC patents': 1145,
      Active: '1979-2016',
      Mainfieldsofinvention:
        'Semiconductor device fabrication, Semiconductor memory, Semiconductor device',
    },
    {
      Inventor: 'Louis L. Hsu',
      NumberofPatentFamilies: 551,
      Country: 'USA',
      'Number of INPADOC patents': 914,
      Active: '1988-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Edwin H. Land',
      NumberofPatentFamilies: 535,
      Country: 'USA',
      'Number of INPADOC patents': 1236,
      Active: '1909(b)-1991(d)',
      Mainfieldsofinvention: 'Instant photography, Polarizing film',
    },
    {
      Inventor: 'Henri Dreyfus',
      NumberofPatentFamilies: 524,
      Country: 'Switzerland',
      'Number of INPADOC patents': 2117,
      Active: '1882(b)-1944(d)',
      Mainfieldsofinvention: 'Polymers, Synthetic fibers, Dyes',
    },
    {
      Inventor: 'Bruce B. Doris',
      NumberofPatentFamilies: 522,
      Country: 'USA',
      'Number of INPADOC patents': 867,
      Active: '1995-2016',
      Mainfieldsofinvention:
        'Integrated Circuits, CMOS, DRAM, Semiconductor device fabrication',
    },
    {
      Inventor: 'Clyde C. Farmer',
      NumberofPatentFamilies: 513,
      Country: 'USA',
      'Number of INPADOC patents': 830,
      Active: '18??(b)-19??(d)',
      Mainfieldsofinvention: 'Railway air brakes',
    },
    {
      Inventor: 'Heinz Focke',
      NumberofPatentFamilies: 512,
      Country: 'Germany',
      'Number of INPADOC patents': 2896,
      Active: '1976-2013',
      Mainfieldsofinvention: 'Cigarette packaging',
    },
    {
      Inventor: 'Mark I. Gardner',
      NumberofPatentFamilies: 511,
      Country: 'USA',
      'Number of INPADOC patents': 587,
      Active: '1994-2010',
      Mainfieldsofinvention:
        'Consumer electronics, Energy, Computers, Semiconductors, Physics',
    },
    {
      Inventor: 'Ravi K. Arimilli',
      NumberofPatentFamilies: 506,
      Country: 'India',
      'Number of INPADOC patents': 767,
      Active: '1992-2016',
      Mainfieldsofinvention:
        'Computer architecture, Semiconductor memory, Cache coherence, Symmetric multiprocessing',
    },
    {
      Inventor: 'Louis H. Morin',
      NumberofPatentFamilies: 503,
      Country: 'USA',
      'Number of INPADOC patents': 720,
      Active: '18??(b)-19??(d)',
      Mainfieldsofinvention: 'Fasteners, Locks, Bobbins',
    },
    {
      Inventor: 'Tobin A. King',
      NumberofPatentFamilies: 497,
      Country: 'Australia',
      'Number of INPADOC patents': 1218,
      Active: '2000-2015',
      Mainfieldsofinvention: 'Printing, Digital paper, Mechanical',
    },
    {
      Inventor: 'Eric C. Leuthardt',
      NumberofPatentFamilies: 495,
      Country: 'USA',
      'Number of INPADOC patents': 1274,
      Active: '2006-2016',
      Mainfieldsofinvention: 'Medical devices',
    },
    {
      Inventor: 'Ali Khakifirooz',
      NumberofPatentFamilies: 489,
      Country: 'USA',
      'Number of INPADOC patents': 737,
      Active: '2011-2016',
      Mainfieldsofinvention:
        'Integrated Circuits, CMOS, Semiconductor device fabrication',
    },
    {
      Inventor: 'Jack A. Mandelman',
      NumberofPatentFamilies: 481,
      Country: 'USA',
      'Number of INPADOC patents': 889,
      Active: '1987-2014',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Jeffrey P. Gambino',
      NumberofPatentFamilies: 479,
      Country: 'USA',
      'Number of INPADOC patents': 798,
      Active: '1992-2016',
      Mainfieldsofinvention:
        'MEMS, CMOS, BiCMOS, DRAM, Image Sensors, RF, Biosensors, 3D Integrated Circuits',
    },
    {
      Inventor: 'John M. Santosuosso',
      NumberofPatentFamilies: 473,
      Country: 'USA',
      'Number of INPADOC patents': 683,
      Active: '2001-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'James M. Hart',
      NumberofPatentFamilies: 464,
      Country: 'USA',
      'Number of INPADOC patents': 1145,
      Active: '1988-2016',
      Mainfieldsofinvention: 'Motor vehicle transmission',
    },
    {
      Inventor: 'Eberhard Ammermann',
      NumberofPatentFamilies: 451,
      Country: 'Germany',
      'Number of INPADOC patents': 5178,
      Active: '1979-2015',
      Mainfieldsofinvention: 'Fungicides',
    },
    {
      Inventor: 'Thomas E. Murray',
      NumberofPatentFamilies: 449,
      Country: 'USA',
      'Number of INPADOC patents': 462,
      Active: '1860(b)-1929(d)',
      Mainfieldsofinvention:
        'Electrical, HVAC, Wheels, Metal working, Light dimmer',
    },
    {
      Inventor: 'Akira Nakazawa',
      NumberofPatentFamilies: 445,
      Country: 'Australia',
      'Number of INPADOC patents': 1340,
      Active: '1980-2016',
      Mainfieldsofinvention: 'Printing, Mechanical',
    },
    {
      Inventor: 'Hongyong Zhang',
      NumberofPatentFamilies: 440,
      Country: 'Japan',
      'Number of INPADOC patents': 858,
      Active: '1993-2016',
      Mainfieldsofinvention: 'Thin film transistors, Liquid crystal displays',
    },
    {
      Inventor: 'Ronald S. Cok',
      NumberofPatentFamilies: 436,
      Country: 'USA',
      'Number of INPADOC patents': 747,
      Active: '1986-2016',
      Mainfieldsofinvention: 'OLED displays; image processing',
    },
    {
      Inventor: 'fe',
      NumberofPatentFamilies: 430,
      Country: 'USA',
      'Number of INPADOC patents': 1759,
      Active: '1983-2016',
      Mainfieldsofinvention: 'Biotechnology, Drug delivery, Tissue engineering',
    },
    {
      Inventor: 'Scott H. Wittkopp',
      NumberofPatentFamilies: 429,
      Country: 'USA',
      'Number of INPADOC patents': 1010,
      Active: '2001-2016',
      Mainfieldsofinvention: 'Motor vehicle transmission',
    },
    {
      Inventor: 'John Hays Hammond, Jr.',
      NumberofPatentFamilies: 417,
      Country: 'USA',
      'Number of INPADOC patents': 460,
      Active: '1888(b)-1965(d)',
      Mainfieldsofinvention: 'Radio control, Radio communications, Torpedoes',
    },
    {
      Inventor: 'Wilhelm Brandes',
      NumberofPatentFamilies: 411,
      Country: 'Germany',
      'Number of INPADOC patents': 2923,
      Active: '1976-2010',
      Mainfieldsofinvention: 'Fungicides',
    },
    {
      Inventor: 'Anthony K. Stamper',
      NumberofPatentFamilies: 411,
      Country: 'USA',
      'Number of INPADOC patents': 726,
      Active: '1998-2016',
      Mainfieldsofinvention: 'MEMS, CMOS, BiCMOS, Silicon-germanium',
    },
    {
      Inventor: 'Hossein Eslambolchi',
      NumberofPatentFamilies: 410,
      Country: 'USA',
      'Number of INPADOC patents': 631,
      Active: '1993-2016',
      Mainfieldsofinvention:
        'Telecommunications, Network intelligence, information Technology, communications technology',
    },
    {
      Inventor: 'Stanford R. Ovshinsky',
      NumberofPatentFamilies: 400,
      Country: 'USA',
      'Number of INPADOC patents': 1649,
      Active: '1922(b)-2012(d)',
      Mainfieldsofinvention:
        'Batteries, Solar cells, Liquid crystal displays, Hydrogen fuel cells, Computer data storage',
    },
    {
      Inventor: 'Victoria Y. H. Wood',
      NumberofPatentFamilies: 400,
      Country: 'USA',
      'Number of INPADOC patents': 1045,
      Active: '2009-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Josef Theurer',
      NumberofPatentFamilies: 388,
      Country: 'Austria',
      'Number of INPADOC patents': 5085,
      Active: '1976-2016',
      Mainfieldsofinvention: 'Railroad maintenance machines',
    },
    {
      Inventor: 'Cary L. Bates',
      NumberofPatentFamilies: 384,
      Country: 'USA',
      'Number of INPADOC patents': 570,
      Active: '1994-2016',
      Mainfieldsofinvention: 'Programming tools, DBX, Memory debuggers',
    },
    {
      Inventor: 'David V. Horak',
      NumberofPatentFamilies: 380,
      Country: 'USA',
      'Number of INPADOC patents': 616,
      Active: '1992-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Kai-Li Jiang',
      NumberofPatentFamilies: 379,
      Country: 'China',
      'Number of INPADOC patents': 829,
      Active: '2006-2016',
      Mainfieldsofinvention:
        'Carbon nanotubes and applications of carbon nanotubes',
    },
    {
      Inventor: 'Hans-Joachim Santel',
      NumberofPatentFamilies: 377,
      Country: 'Germany',
      'Number of INPADOC patents': 2623,
      Active: '1986-2013',
      Mainfieldsofinvention: 'Herbicides, Pesticides, Organic chemistry',
    },
    {
      Inventor: 'Xuemin (Sherman) Chen',
      NumberofPatentFamilies: 377,
      Country: 'USA',
      'Number of INPADOC patents': 1151,
      Active: '1997-2017',
      Mainfieldsofinvention:
        'Computer networks, Integrated Circuits, Signal Processing',
    },
    {
      Inventor: 'George P. Liang',
      NumberofPatentFamilies: 375,
      Country: 'China',
      'Number of INPADOC patents': 508,
      Active: '1983-2016',
      Mainfieldsofinvention: 'Gas turbine cooling',
    },
    {
      Inventor: 'Gisela Lorenz',
      NumberofPatentFamilies: 374,
      Country: 'Germany',
      'Number of INPADOC patents': 4155,
      Active: '1990-2015',
      Mainfieldsofinvention: 'Fungicides, Organic chemistry',
    },
    {
      Inventor: 'Garry R. Jackson',
      NumberofPatentFamilies: 367,
      Country: 'Australia',
      'Number of INPADOC patents': 656,
      Active: '2001-2016',
      Mainfieldsofinvention: 'Printing, Mechanical',
    },
    {
      Inventor: 'Paul W. Dent',
      NumberofPatentFamilies: 362,
      Country: 'USA',
      'Number of INPADOC patents': 2252,
      Active: '1984-2015',
      Mainfieldsofinvention: 'Wireless communications',
    },
    {
      Inventor: 'George Westinghouse',
      NumberofPatentFamilies: 361,
      Country: 'USA',
      'Number of INPADOC patents': 0,
      Active: '1846(b)-1914(d)',
      Mainfieldsofinvention:
        'Electric power, Electricity meter, Railway air brake, Steam engines',
    },
    {
      Inventor: 'Wael W. Diab',
      NumberofPatentFamilies: 358,
      Country: 'USA',
      'Number of INPADOC patents': 774,
      Active: '2003-2016',
      Mainfieldsofinvention: 'Computer networks',
    },
    {
      Inventor: 'Devendra K. Sadana',
      NumberofPatentFamilies: 356,
      Country: 'India',
      'Number of INPADOC patents': 794,
      Active: '1983-2016',
      Mainfieldsofinvention:
        'Solar cells, OLED, Integrated Circuits, CMOS, DRAM, LEDs',
    },
    {
      Inventor: 'Vincent J. Zimmer',
      NumberofPatentFamilies: 354,
      Country: 'USA',
      'Number of INPADOC patents': 972,
      Active: '1999-2016',
      Mainfieldsofinvention: 'Computer software and firmware',
    },
    {
      Inventor: 'Robert R. Schmidt',
      NumberofPatentFamilies: 350,
      Country: 'Germany',
      'Number of INPADOC patents': 2467,
      Active: '1971-2005',
      Mainfieldsofinvention: 'Herbicides, Fungicides, Organic chemistry',
    },
    {
      Inventor: 'Norman M. Berry',
      NumberofPatentFamilies: 347,
      Country: 'Australia',
      'Number of INPADOC patents': 516,
      Active: '2006-2016',
      Mainfieldsofinvention: 'Printing, Mechanical',
    },
    {
      Inventor: 'Chih-Chao Yang',
      NumberofPatentFamilies: 345,
      Country: 'USA',
      'Number of INPADOC patents': 690,
      Active: '2003-2016',
      Mainfieldsofinvention: 'Integrated Circuits',
    },
    {
      Inventor: 'Gregory J. Boss',
      NumberofPatentFamilies: 345,
      Country: 'USA',
      'Number of INPADOC patents': 588,
      Active: '2008-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Mark W. Kroll',
      NumberofPatentFamilies: 343,
      Country: 'USA',
      'Number of INPADOC patents': 460,
      Active: '1987-2016',
      Mainfieldsofinvention: 'Implantable medical devices',
    },
    {
      Inventor: "Brian M. O'Connell",
      NumberofPatentFamilies: 331,
      Country: 'USA',
      'Number of INPADOC patents': 592,
      Active: '2009-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'William Daniel Hillis',
      NumberofPatentFamilies: 328,
      Country: 'USA',
      'Number of INPADOC patents': 229,
      Active: '1986-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Brent A. Anderson',
      NumberofPatentFamilies: 323,
      Country: 'USA',
      'Number of INPADOC patents': 454,
      Active: '2001-2016',
      Mainfieldsofinvention:
        'Semiconductor device fabrication, Semiconductor memory, Semiconductor device',
    },
    {
      Inventor: 'Jeffrey E. Stahmann',
      NumberofPatentFamilies: 321,
      Country: 'USA',
      'Number of INPADOC patents': 640,
      Active: '1994-2016',
      Mainfieldsofinvention: 'Medical devices',
    },
    {
      Inventor: 'Carl J. Radens',
      NumberofPatentFamilies: 317,
      Country: 'USA',
      'Number of INPADOC patents': 636,
      Active: '1994-2016',
      Mainfieldsofinvention:
        'Integrated Circuits, CMOS, DRAM, Semiconductor device fabrication',
    },
    {
      Inventor: 'Clifford A. Pickover',
      NumberofPatentFamilies: 317,
      Country: 'USA',
      'Number of INPADOC patents': 653,
      Active: '1992-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Liang Liu',
      NumberofPatentFamilies: 310,
      Country: 'China',
      'Number of INPADOC patents': 777,
      Active: '2005-2016',
      Mainfieldsofinvention:
        'Carbon nanotubes and applications of carbon nanotubes',
    },
    {
      Inventor: 'Steven L. Teig',
      NumberofPatentFamilies: 307,
      Country: 'USA',
      'Number of INPADOC patents': 366,
      Active: '1995-2016',
      Mainfieldsofinvention: 'Integrated Circuits',
    },
    {
      Inventor: 'Victoria Smith',
      NumberofPatentFamilies: 305,
      Country: 'USA',
      'Number of INPADOC patents': 2040,
      Active: '2006-2016',
      Mainfieldsofinvention: 'Proteins, Antibodies',
    },
    {
      Inventor: 'Robert G. LeTourneau',
      NumberofPatentFamilies: 299,
      Country: 'USA',
      'Number of INPADOC patents': 67,
      Active: '1888(b)-1969(d)',
      Mainfieldsofinvention:
        'Earthworks (engineering), Heavy Equipment, Industrial Machinery',
    },
    {
      Inventor: 'William R. Tonti',
      NumberofPatentFamilies: 291,
      Country: 'USA',
      'Number of INPADOC patents': 441,
      Active: '1994-2016',
      Mainfieldsofinvention:
        'Integrated Circuits, CMOS, DRAM, Semiconductor device fabrication',
    },
    {
      Inventor: 'Keith R. Walker',
      NumberofPatentFamilies: 282,
      Country: 'Saudi Arabia',
      'Number of INPADOC patents': 318,
      Active: '2003-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Victor S. Moore',
      NumberofPatentFamilies: 280,
      Country: 'USA',
      'Number of INPADOC patents': 428,
      Active: '1982-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Hanson S. Gifford III',
      NumberofPatentFamilies: 276,
      Country: 'USA',
      'Number of INPADOC patents': 795,
      Active: '1987-2016',
      Mainfieldsofinvention: 'Medical Devices',
    },
    {
      Inventor: 'Daniel J. Winarski',
      NumberofPatentFamilies: 275,
      Country: 'USA',
      'Number of INPADOC patents': 506,
      Active: '1982-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Adam Heller',
      NumberofPatentFamilies: 272,
      Country: 'Romania',
      'Number of INPADOC patents': 711,
      Active: '1968-2016',
      Mainfieldsofinvention: 'Solar cells, Glucose meters, Lasers',
    },
    {
      Inventor: 'Lisa Seacat DeLuca',
      NumberofPatentFamilies: 271,
      Country: 'USA',
      'Number of INPADOC patents': 385,
      Active: '2009-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Brent Keeth',
      NumberofPatentFamilies: 270,
      Country: 'USA',
      'Number of INPADOC patents': 470,
      Active: '1994-2016',
      Mainfieldsofinvention: 'Integrated Circuits, CMOS, DRAM',
    },
    {
      Inventor: 'Hartley Owen',
      NumberofPatentFamilies: 267,
      Country: 'USA',
      'Number of INPADOC patents': 751,
      Active: '1976-2010',
      Mainfieldsofinvention: 'Fluid catalytic cracking',
    },
    {
      Inventor: 'Michael A. Rothman',
      NumberofPatentFamilies: 256,
      Country: 'USA',
      'Number of INPADOC patents': 687,
      Active: '2001-2017',
      Mainfieldsofinvention: 'Computer software and firmware',
    },
    {
      Inventor: 'Yoshihiro Kikuchi',
      NumberofPatentFamilies: 255,
      Country: 'Japan',
      'Number of INPADOC patents': 1120,
      Active: '1994-2015',
      Mainfieldsofinvention: 'Video processing',
    },
    {
      Inventor: 'Kulvir S. Bhogal',
      NumberofPatentFamilies: 252,
      Country: 'USA',
      'Number of INPADOC patents': 486,
      Active: '2003-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Bengt Lindoff',
      NumberofPatentFamilies: 248,
      Country: 'Sweden',
      'Number of INPADOC patents': 1658,
      Active: '2000-2017',
      Mainfieldsofinvention: 'Wireless communications',
    },
    {
      Inventor: 'Nobuyuki Taniguchi',
      NumberofPatentFamilies: 245,
      Country: 'Japan',
      'Number of INPADOC patents': 967,
      Active: '1979-2015',
      Mainfieldsofinvention: 'Cameras',
    },
    {
      Inventor: 'Dean L. Kamen',
      NumberofPatentFamilies: 243,
      Country: 'USA',
      'Number of INPADOC patents': 1186,
      Active: '1979-2016',
      Mainfieldsofinvention:
        'Battery-powered electric vehicles, Medical devices, Stirling engines, Water purification, Wheelchairs',
    },
    {
      Inventor: 'Philip S. Yu',
      NumberofPatentFamilies: 236,
      Country: 'USA',
      'Number of INPADOC patents': 158,
      Active: '1982-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Rajiv V. Joshi',
      NumberofPatentFamilies: 235,
      Country: 'USA',
      'Number of INPADOC patents': 354,
      Active: '1986-2016',
      Mainfieldsofinvention: 'Electronics, analytics',
    },
    {
      Inventor: 'Lawrence A. Clevenger',
      NumberofPatentFamilies: 235,
      Country: 'USA',
      'Number of INPADOC patents': 526,
      Active: '1996-2017',
      Mainfieldsofinvention:
        'Semiconductor, Cognitive, Memory, Security, Analytics',
    },
    {
      Inventor: 'Johnny M. Shieh',
      NumberofPatentFamilies: 231,
      Country: 'USA',
      'Number of INPADOC patents': 444,
      Active: '1996-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Takeshi Chujoh',
      NumberofPatentFamilies: 229,
      Country: 'Japan',
      'Number of INPADOC patents': 1065,
      Active: '1995-2016',
      Mainfieldsofinvention: 'Video processing',
    },
    {
      Inventor: 'Bran Ferren',
      NumberofPatentFamilies: 225,
      Country: 'USA',
      'Number of INPADOC patents': 589,
      Active: '1986-2017',
      Mainfieldsofinvention:
        'Computers, Consumer Electronics, Optical Systems, Medical, User Interfaces, Automotive',
    },
    {
      Inventor: 'Paul Ian Mackey',
      NumberofPatentFamilies: 220,
      Country: 'Australia',
      'Number of INPADOC patents': 246,
      Active: '2008-2016',
      Mainfieldsofinvention: 'Printing, Mechanical',
    },
    {
      Inventor: 'Louis Rosenberg',
      NumberofPatentFamilies: 218,
      Country: 'USA',
      'Number of INPADOC patents': 444,
      Active: '1995-2016',
      Mainfieldsofinvention: 'Augmented Reality, Virtual Reality, A.I., HCI',
    },
    {
      Inventor: 'Thomas J. Kennedy III',
      NumberofPatentFamilies: 218,
      Country: 'USA',
      'Number of INPADOC patents': 513,
      Active: '1992-2016',
      Mainfieldsofinvention: 'Sporting Goods, Wind Turbines',
    },
    {
      Inventor: 'Gerald F. McBrearty',
      NumberofPatentFamilies: 213,
      Country: 'USA',
      'Number of INPADOC patents': 387,
      Active: '1997-2016',
      Mainfieldsofinvention: 'Various',
    },
    {
      Inventor: 'Esmael H. Dinan',
      NumberofPatentFamilies: 208,
      Country: 'USA',
      'Number of INPADOC patents': 344,
      Active: '2000-2017',
      Mainfieldsofinvention: 'Communication Networks',
    },
    {
      Inventor: 'Imad Libbus',
      NumberofPatentFamilies: 207,
      Country: 'USA',
      'Number of INPADOC patents': 472,
      Active: '2007-2017',
      Mainfieldsofinvention: 'Medical devices',
    },
    {
      Inventor: 'Hiroshi (You) Yoshioka',
      NumberofPatentFamilies: 205,
      Country: 'Japan',
      'Number of INPADOC patents': 181,
      Active: '1997-2015',
      Mainfieldsofinvention: 'Cameras',
    },
    {
      Inventor: 'Patrick B. Usoro',
      NumberofPatentFamilies: 205,
      Country: 'USA',
      'Number of INPADOC patents': 343,
      Active: '1999-2016',
      Mainfieldsofinvention:
        'Transmissions, Hybrid Powertrains, Vehicle Thermal Management',
    },
    {
      Inventor: 'Gregory McAvoy',
      NumberofPatentFamilies: 205,
      Country: 'Australia',
      'Number of INPADOC patents': 433,
      Active: '2003-2014',
      Mainfieldsofinvention: 'Printing, MEMS',
    },
    {
      Inventor: 'Sebastian T Ventrone',
      NumberofPatentFamilies: 204,
      Country: 'USA',
      'Number of INPADOC patents': 283,
      Active: '1989-2017',
      Mainfieldsofinvention: 'Semiconductor, Logic, Architecture',
    },
    {
      Inventor: 'Dorin Comaniciu',
      NumberofPatentFamilies: 200,
      Country: 'USA',
      'Number of INPADOC patents': 452,
      Active: '2003-2017',
      Mainfieldsofinvention:
        'Machine Intelligence, Medical Imaging, Image-Guided Surgery, Computer Vision',
    },
  ];
  