export const categoryData: Object[] = [
    {
      CategoryName: 'Beverages',
      ProductID: 1,
      ProductName: 'Chai',
      SupplierID: 1,
      QuantityPerUnit: '10 boxes x 20 bags',
      UnitPrice: 18.0,
      UnitsInStock: 39,
      Delivered: true,
    },
  
    {
      CategoryName: 'Beverages',
      ProductID: 2,
      ProductName: 'Chang',
      SupplierID: 1,
      QuantityPerUnit: '24 - 12 oz bottles',
      UnitPrice: 19.0,
      UnitsInStock: 17,
      Delivered: true,
    },
  
    {
      CategoryName: 'Beverages',
      ProductID: 3,
      ProductName: 'Aniseed Syrup',
      SupplierID: 1,
      QuantityPerUnit: '12 - 550 ml bottles',
      UnitPrice: 10.0,
      UnitsInStock: 13,
      Delivered: true,
    },
  
    {
      CategoryName: 'Beverages',
      ProductID: 4,
      ProductName: "Chef Anton's Cajun Seasoning",
      SupplierID: 2,
      QuantityPerUnit: '48 - 6 oz jars',
      UnitPrice: 22.0,
      UnitsInStock: 53,
      Delivered: true,
    },
  
    {
      CategoryName: 'Beverages',
      ProductID: 5,
      ProductName: "Chef Anton's Gumbo Mix",
      SupplierID: 2,
      QuantityPerUnit: '36 boxes',
      UnitPrice: 21.35,
      UnitsInStock: 0,
      Delivered: true,
    },
  
    {
      CategoryName: 'Beverages',
      ProductID: 6,
      ProductName: "Grandma's Boysenberry Spread",
      SupplierID: 3,
      QuantityPerUnit: '12 - 8 oz jars',
      UnitPrice: 25.0,
      UnitsInStock: 120,
      Delivered: false,
    },
  
    {
      CategoryName: 'Beverages',
      ProductID: 7,
      ProductName: "Uncle Bob's Organic Dried Pears",
      SupplierID: 3,
      QuantityPerUnit: '12 - 1 lb pkgs.',
      UnitPrice: 30.0,
      UnitsInStock: 15,
      Delivered: false,
    },
  
    {
      CategoryName: 'Beverages',
      ProductID: 8,
      ProductName: 'Northwoods Cranberry Sauce',
      SupplierID: 3,
      QuantityPerUnit: '12 - 12 oz jars',
      UnitPrice: 40.0,
      UnitsInStock: 6,
      Delivered: false,
    },
  
    {
      CategoryName: 'Beverages',
      ProductID: 9,
      ProductName: 'Mishi Kobe Niku',
      SupplierID: 4,
      QuantityPerUnit: '18 - 500 g pkgs.',
      UnitPrice: 97.0,
      UnitsInStock: 29,
      Delivered: true,
    },
  
    {
      CategoryName: 'Beverages',
      ProductID: 10,
      ProductName: 'Ikura',
      SupplierID: 4,
      QuantityPerUnit: '12 - 200 ml jars',
      UnitPrice: 31.0,
      UnitsInStock: 31,
      Delivered: false,
    },
  
    {
      CategoryName: 'Beverages',
      ProductID: 11,
      ProductName: 'Queso Cabrales',
      SupplierID: 5,
      QuantityPerUnit: '1 kg pkg.',
      UnitPrice: 21.0,
      UnitsInStock: 22,
      Delivered: false,
    },
  
    {
      CategoryName: 'Condiments',
      ProductID: 12,
      ProductName: 'Queso Manchego La Pastora',
      SupplierID: 5,
      QuantityPerUnit: '10 - 500 g pkgs.',
      UnitPrice: 38.0,
      UnitsInStock: 86,
      Delivered: false,
    },
  
    {
      CategoryName: 'Condiments',
      ProductID: 13,
      ProductName: 'Konbu',
      SupplierID: 6,
      QuantityPerUnit: '2 kg box',
      UnitPrice: 6.0,
      UnitsInStock: 24,
      Delivered: true,
    },
  
    {
      CategoryName: 'Condiments',
      ProductID: 14,
      ProductName: 'Tofu',
      SupplierID: 6,
      QuantityPerUnit: '40 - 100 g pkgs.',
      UnitPrice: 23.25,
      UnitsInStock: 35,
      Delivered: true,
    },
  
    {
      CategoryName: 'Condiments',
      ProductID: 15,
      ProductName: 'Genen Shouyu',
      SupplierID: 6,
      QuantityPerUnit: '24 - 250 ml bottles',
      UnitPrice: 15.5,
      UnitsInStock: 39,
      Delivered: true,
    },
  
    {
      CategoryName: 'Condiments',
      ProductID: 16,
      ProductName: 'Pavlova',
      SupplierID: 7,
      QuantityPerUnit: '32 - 500 g boxes',
      UnitPrice: 17.45,
      UnitsInStock: 29,
      Delivered: true,
    },
  
    {
      CategoryName: 'Condiments',
      ProductID: 17,
      ProductName: 'Alice Mutton',
      SupplierID: 7,
      QuantityPerUnit: '20 - 1 kg tins',
      UnitPrice: 39.0,
      UnitsInStock: 0,
      Delivered: true,
    },
  
    {
      CategoryName: 'Condiments',
      ProductID: 18,
      ProductName: 'Carnarvon Tigers',
      SupplierID: 7,
      QuantityPerUnit: '16 kg pkg.',
      UnitPrice: 62.5,
      UnitsInStock: 42,
      Delivered: false,
    },
  
    {
      CategoryName: 'Condiments',
      ProductID: 19,
      ProductName: 'Teatime Chocolate Biscuits',
      SupplierID: 8,
      QuantityPerUnit: '10 boxes x 12 pieces',
      UnitPrice: 9.2,
      UnitsInStock: 25,
      Delivered: false,
    },
  
    {
      CategoryName: 'Condiments',
      ProductID: 20,
      ProductName: "Sir Rodney's Marmalade",
      SupplierID: 8,
      QuantityPerUnit: '30 gift boxes',
      UnitPrice: 81.0,
      UnitsInStock: 40,
      Delivered: false,
    },
  
    {
      CategoryName: 'Condiments',
      ProductID: 21,
      ProductName: "Sir Rodney's Scones",
      SupplierID: 8,
      QuantityPerUnit: '24 pkgs. x 4 pieces',
      UnitPrice: 10.0,
      UnitsInStock: 3,
      Delivered: false,
    },
  
    {
      CategoryName: 'Condiments',
      ProductID: 22,
      ProductName: "Gustaf's Knäckebröd",
      SupplierID: 9,
      QuantityPerUnit: '24 - 500 g pkgs.',
      UnitPrice: 21.0,
      UnitsInStock: 104,
      Delivered: false,
    },
  
    {
      CategoryName: 'Confections',
      ProductID: 23,
      ProductName: 'Tunnbröd',
      SupplierID: 9,
      QuantityPerUnit: '12 - 250 g pkgs.',
      UnitPrice: 9.0,
      UnitsInStock: 61,
      Delivered: false,
    },
  
    {
      CategoryName: 'Confections',
      ProductID: 24,
      ProductName: 'Guaraná Fantástica',
      SupplierID: 10,
      QuantityPerUnit: '12 - 355 ml cans',
      UnitPrice: 4.5,
      UnitsInStock: 20,
      Delivered: true,
    },
  
    {
      CategoryName: 'Confections',
      ProductID: 25,
      ProductName: 'NuNuCa Nuß-Nougat-Creme',
      SupplierID: 11,
      QuantityPerUnit: '20 - 450 g glasses',
      UnitPrice: 14.0,
      UnitsInStock: 76,
      Delivered: false,
    },
  
    {
      CategoryName: 'Confections',
      ProductID: 26,
      ProductName: 'Gumbär Gummibärchen',
      SupplierID: 11,
      QuantityPerUnit: '100 - 250 g bags',
      UnitPrice: 31.23,
      UnitsInStock: 15,
      Delivered: true,
    },
  
    {
      CategoryName: 'Confections',
      ProductID: 27,
      ProductName: 'Schoggi Schokolade',
      SupplierID: 11,
      QuantityPerUnit: '100 - 100 g pieces',
      UnitPrice: 43.9,
      UnitsInStock: 49,
      Delivered: true,
    },
  
    {
      CategoryName: 'Confections',
      ProductID: 28,
      ProductName: 'Rössle Sauerkraut',
      SupplierID: 12,
      QuantityPerUnit: '25 - 825 g cans',
      UnitPrice: 45.6,
      UnitsInStock: 26,
      Delivered: true,
    },
  
    {
      CategoryName: 'Confections',
      ProductID: 29,
      ProductName: 'Thüringer Rostbratwurst',
      SupplierID: 12,
      QuantityPerUnit: '50 bags x 30 sausgs.',
      UnitPrice: 123.79,
      UnitsInStock: 0,
      Delivered: true,
    },
  
    {
      CategoryName: 'Confections',
      ProductID: 30,
      ProductName: 'Nord-Ost Matjeshering',
      SupplierID: 13,
      QuantityPerUnit: '10 - 200 g glasses',
      UnitPrice: 25.89,
      UnitsInStock: 10,
      Delivered: true,
    },
  
    {
      CategoryName: 'Confections',
      ProductID: 31,
      ProductName: 'Gorgonzola Telino',
      SupplierID: 14,
      QuantityPerUnit: '12 - 100 g pkgs',
      UnitPrice: 12.5,
      UnitsInStock: 0,
      Delivered: true,
    },
  
    {
      CategoryName: 'Confections',
      ProductID: 32,
      ProductName: 'Mascarpone Fabioli',
      SupplierID: 14,
      QuantityPerUnit: '24 - 200 g pkgs.',
      UnitPrice: 32.0,
      UnitsInStock: 9,
      Delivered: false,
    },
  
    {
      CategoryName: 'Confections',
      ProductID: 33,
      ProductName: 'Geitost',
      SupplierID: 15,
      QuantityPerUnit: '500 g',
      UnitPrice: 2.5,
      UnitsInStock: 112,
      Delivered: false,
    },
  
    {
      CategoryName: 'Confections',
      ProductID: 34,
      ProductName: 'Sasquatch Ale',
      SupplierID: 16,
      QuantityPerUnit: '24 - 12 oz bottles',
      UnitPrice: 14.0,
      UnitsInStock: 111,
      Delivered: false,
    },
  
    {
      CategoryName: 'Confections',
      ProductID: 35,
      ProductName: 'Steeleye Stout',
      SupplierID: 16,
      QuantityPerUnit: '24 - 12 oz bottles',
      UnitPrice: 18.0,
      UnitsInStock: 20,
      Delivered: false,
    },
  
    {
      CategoryName: 'Dairy Products',
      ProductID: 36,
      ProductName: 'Inlagd Sill',
      SupplierID: 17,
      QuantityPerUnit: '24 - 250 g  jars',
      UnitPrice: 19.0,
      UnitsInStock: 112,
      Delivered: false,
    },
  
    {
      CategoryName: 'Dairy Products',
      ProductID: 37,
      ProductName: 'Gravad lax',
      SupplierID: 17,
      QuantityPerUnit: '12 - 500 g pkgs.',
      UnitPrice: 26.0,
      UnitsInStock: 11,
      Delivered: false,
    },
  
    {
      CategoryName: 'Dairy Products',
      ProductID: 38,
      ProductName: 'Côte de Blaye',
      SupplierID: 18,
      QuantityPerUnit: '12 - 75 cl bottles',
      UnitPrice: 263.5,
      UnitsInStock: 17,
      Delivered: false,
    },
  
    {
      CategoryName: 'Dairy Products',
      ProductID: 39,
      ProductName: 'Chartreuse verte',
      SupplierID: 18,
      QuantityPerUnit: '750 cc per bottle',
      UnitPrice: 18.0,
      UnitsInStock: 69,
      Delivered: true,
    },
  
    {
      CategoryName: 'Dairy Products',
      ProductID: 40,
      ProductName: 'Boston Crab Meat',
      SupplierID: 19,
      QuantityPerUnit: '24 - 4 oz tins',
      UnitPrice: 18.4,
      UnitsInStock: 123,
      Delivered: true,
    },
  
    {
      CategoryName: 'Dairy Products',
      ProductID: 41,
      ProductName: "Jack's New England Clam Chowder",
      SupplierID: 19,
      QuantityPerUnit: '12 - 12 oz cans',
      UnitPrice: 9.65,
      UnitsInStock: 85,
      Delivered: false,
    },
  
    {
      CategoryName: 'Dairy Products',
      ProductID: 42,
      ProductName: 'Singaporean Hokkien Fried Mee',
      SupplierID: 20,
      QuantityPerUnit: '32 - 1 kg pkgs.',
      UnitPrice: 14.0,
      UnitsInStock: 26,
      Delivered: true,
    },
  
    {
      CategoryName: 'Dairy Products',
      ProductID: 43,
      ProductName: 'Ipoh Coffee',
      SupplierID: 20,
      QuantityPerUnit: '16 - 500 g tins',
      UnitPrice: 46.0,
      UnitsInStock: 17,
      Delivered: false,
    },
  
    {
      CategoryName: 'Dairy Products',
      ProductID: 44,
      ProductName: 'Gula Malacca',
      SupplierID: 20,
      QuantityPerUnit: '20 - 2 kg bags',
      UnitPrice: 19.45,
      UnitsInStock: 27,
      Delivered: false,
    },
  
    {
      CategoryName: 'Dairy Products',
      ProductID: 45,
      ProductName: 'Rogede sild',
      SupplierID: 21,
      QuantityPerUnit: '1k pkg.',
      UnitPrice: 9.5,
      UnitsInStock: 5,
      Delivered: true,
    },
  
    {
      CategoryName: 'Grains/Cereals',
      ProductID: 46,
      ProductName: 'Spegesild',
      SupplierID: 21,
      QuantityPerUnit: '4 - 450 g glasses',
      UnitPrice: 12.0,
      UnitsInStock: 95,
      Delivered: true,
    },
  
    {
      CategoryName: 'Grains/Cereals',
      ProductID: 47,
      ProductName: 'Zaanse koeken',
      SupplierID: 22,
      QuantityPerUnit: '10 - 4 oz boxes',
      UnitPrice: 9.5,
      UnitsInStock: 36,
      Delivered: true,
    },
  
    {
      CategoryName: 'Grains/Cereals',
      ProductID: 48,
      ProductName: 'Chocolade',
      SupplierID: 22,
      QuantityPerUnit: '10 pkgs.',
      UnitPrice: 12.75,
      UnitsInStock: 15,
      Delivered: true,
    },
  
    {
      CategoryName: 'Grains/Cereals',
      ProductID: 49,
      ProductName: 'Maxilaku',
      SupplierID: 23,
      QuantityPerUnit: '24 - 50 g pkgs.',
      UnitPrice: 20.0,
      UnitsInStock: 10,
      Delivered: false,
    },
  
    {
      CategoryName: 'Grains/Cereals',
      ProductID: 50,
      ProductName: 'Valkoinen suklaa',
      SupplierID: 23,
      QuantityPerUnit: '12 - 100 g bars',
      UnitPrice: 16.25,
      UnitsInStock: 65,
      Delivered: false,
    },
  
    {
      CategoryName: 'Grains/Cereals',
      ProductID: 51,
      ProductName: 'Manjimup Dried Apples',
      SupplierID: 24,
      QuantityPerUnit: '50 - 300 g pkgs.',
      UnitPrice: 53.0,
      UnitsInStock: 20,
      Delivered: false,
    },
  
    {
      CategoryName: 'Meat/Poultry',
      ProductID: 52,
      ProductName: 'Filo Mix',
      SupplierID: 24,
      QuantityPerUnit: '16 - 2 kg boxes',
      UnitPrice: 7.0,
      UnitsInStock: 38,
      Delivered: true,
    },
  
    {
      CategoryName: 'Meat/Poultry',
      ProductID: 53,
      ProductName: 'Perth Pasties',
      SupplierID: 24,
      QuantityPerUnit: '48 pieces',
      UnitPrice: 32.8,
      UnitsInStock: 0,
      Delivered: true,
    },
  
    {
      CategoryName: 'Produce',
      ProductID: 54,
      ProductName: 'Tourtière',
      SupplierID: 25,
      QuantityPerUnit: '16 pies',
      UnitPrice: 7.45,
      UnitsInStock: 21,
      Delivered: true,
    },
  
    {
      CategoryName: 'Produce',
      ProductID: 55,
      ProductName: 'Pâté chinois',
      SupplierID: 25,
      QuantityPerUnit: '24 boxes x 2 pies',
      UnitPrice: 24.0,
      UnitsInStock: 115,
      Delivered: true,
    },
  
    {
      CategoryName: 'Produce',
      ProductName: 'Gnocchi di nonna Alice',
      SupplierID: 26,
      QuantityPerUnit: '24 - 250 g pkgs.',
      UnitPrice: 38.0,
      UnitsInStock: 21,
      Delivered: false,
    },
  
    {
      CategoryName: 'Produce',
      ProductName: 'Ravioli Angelo',
      SupplierID: 26,
      QuantityPerUnit: '24 - 250 g pkgs.',
      UnitPrice: 19.5,
      UnitsInStock: 36,
      Delivered: false,
    },
  
    {
      CategoryName: 'Seafood',
      ProductID: 58,
      ProductName: 'Escargots de Bourgogne',
      SupplierID: 27,
      QuantityPerUnit: '24 pieces',
      UnitPrice: 13.25,
      UnitsInStock: 62,
      Delivered: false,
    },
  
    {
      CategoryName: 'Seafood',
      ProductID: 59,
      ProductName: 'Raclette Courdavault',
      SupplierID: 28,
      QuantityPerUnit: '5 kg pkg.',
      UnitPrice: 55.0,
      UnitsInStock: 79,
      Delivered: false,
    },
  
    {
      CategoryName: 'Seafood',
      ProductID: 60,
      ProductName: 'Camembert Pierrot',
      SupplierID: 28,
      QuantityPerUnit: '15 - 300 g rounds',
      UnitPrice: 34.0,
      UnitsInStock: 19,
      Delivered: false,
    },
  
    {
      CategoryName: 'Seafood',
      ProductID: 61,
      ProductName: "Sirop d'érable",
      SupplierID: 29,
      QuantityPerUnit: '24 - 500 ml bottles',
      UnitPrice: 28.5,
      UnitsInStock: 113,
      Delivered: false,
    },
  
    {
      CategoryName: 'Seafood',
      ProductID: 62,
      ProductName: 'Tarte au sucre',
      SupplierID: 29,
      QuantityPerUnit: '48 pies',
      UnitPrice: 49.3,
      UnitsInStock: 17,
      Delivered: false,
    },
  
    {
      CategoryName: 'Seafood',
      ProductID: 63,
      ProductName: 'Vegie-spread',
      SupplierID: 7,
      QuantityPerUnit: '15 - 625 g jars',
      UnitPrice: 43.9,
      UnitsInStock: 24,
      Delivered: true,
    },
  
    {
      CategoryName: 'Seafood',
      ProductID: 64,
      ProductName: 'Wimmers gute Semmelknödel',
      SupplierID: 12,
      QuantityPerUnit: '20 bags x 4 pieces',
      UnitPrice: 33.25,
      UnitsInStock: 22,
      Delivered: true,
    },
  
    {
      CategoryName: 'Seafood',
      ProductID: 65,
      ProductName: 'Louisiana Fiery Hot Pepper Sauce',
      SupplierID: 2,
      QuantityPerUnit: '32 - 8 oz bottles',
      UnitPrice: 21.05,
      UnitsInStock: 76,
      Delivered: true,
    },
  
    {
      CategoryName: 'Seafood',
      ProductID: 66,
      ProductName: 'Louisiana Hot Spiced Okra',
      SupplierID: 2,
      QuantityPerUnit: '24 - 8 oz jars',
      UnitPrice: 17.0,
      UnitsInStock: 4,
      Delivered: false,
    },
  
    {
      CategoryName: 'Seafood',
      ProductID: 67,
      ProductName: 'Laughing Lumberjack Lager',
      SupplierID: 16,
      QuantityPerUnit: '24 - 12 oz bottles',
      UnitPrice: 14.0,
      UnitsInStock: 52,
      Delivered: false,
    },
  
    {
      CategoryName: 'Seafood',
      ProductID: 68,
      ProductName: 'Scottish Longbreads',
      SupplierID: 8,
      QuantityPerUnit: '10 boxes x 8 pieces',
      UnitPrice: 12.5,
      UnitsInStock: 6,
      Delivered: false,
    },
  
    {
      CategoryName: 'Seafood',
      ProductID: 69,
      ProductName: 'Gudbrandsdalsost',
      SupplierID: 15,
      QuantityPerUnit: '10 kg pkg.',
      UnitPrice: 36.0,
      UnitsInStock: 26,
      Delivered: false,
    },
  ];
  