


import { enableRipple } from '@syncfusion/ej2-base';
import { L10n } from '@syncfusion/ej2-base';
enableRipple(true);
/**
 * Rich Text Editor localization sample
 */

L10n.load({
    'de-DE': {
        'richtexteditor': {
            alignments: "Ausrichtungen",
            justifyLeft: "Linksbündig",
            justifyCenter: "Im Zentrum anordnen",
            justifyRight: "Rechts ausrichten",
            justifyFull: "Justize ausrichten",
            fontName: "Schriftartenname",
            fontSize: "Schriftgröße",
            fontColor: "Schriftfarbe",
            backgroundColor: "Hintergrundfarbe",
            bold: "Fett gedruckt",
            italic: "Kursiv",
            underline: "Unterstreichen",
            strikethrough: "Durchgestrichen",
            clearFormat: "Format löschen",
            clearAll: "Alles löschen",
            cut: "Schnitt",
            copy: "Kopieren",
            paste: "Einfügen",
            unorderedList: "Liste mit Aufzählungszeichen",
            orderedList: "Nummerierte Liste",
            indent: "Einzug vergrößern",
            outdent: "Einzug verringern",
            undo: "Rückgängig machen",
            redo: "Wiederholen",
            superscript: "Hochgestellt",
            subscript: "Index",
            createLink: "Link einfügen",
            openLink: "Verbindung öffnen",
            editLink: "Link bearbeiten",
            removeLink: "Link entfernen",
            image: "Bild einfügen",
            replace: "Ersetzen",
            align: "Ausrichten",
            caption: "Bildbeschreibung",
            remove: "Löschen",
            insertLink: "Link einfügen",
            display: "Anzeige",
            altText: "alternativer Text",
            dimension: "Größe ändern",
            fullscreen: "Maximieren",
            maximize: "Maximieren",
            minimize: "Minimieren",
            lowerCase: "Kleinbuchstaben",
            upperCase: "Großbuchstaben",
            print: "Drucken",
            formats: "Formate",
            sourcecode: "Codeansicht",
            preview: "Vorschau",
            viewside: "Ansicht Seite",
            insertCode: "Code eingeben",
            linkText: "Text anzeigen",
            linkTooltipLabel: "Titel",
            linkWebUrl: "Webadresse",
            linkTitle: "Titel eingeben",
            linkurl: "http://example.com",
            linkOpenInNewWindow: "Link in neuem Fenster öffnen",
            linkHeader: "Link einfügen",
            dialogInsert: "Einfügen",
            dialogCancel: "Stornieren",
            dialogUpdate: "Aktualisieren",
            imageHeader: "Bild einfügen",
            imageLinkHeader: "Sie können auch einen Link aus dem Web bereitstellen",
            mdimageLink: "Bitte geben Sie eine URL für Ihr Bild an",
            imageUploadMessage: "Bild hier ablegen oder hoch laden",
            imageDeviceUploadMessage: "Klicken Sie hier zum Hochladen",
            imageAlternateText: "Alternativer Text",
            alternateHeader: "alternativer Text",
            browse: "Durchsuche",
            imageUrl: "http://example.com/image.png",
            imageCaption: "Bildbeschriftung",
            imageSizeHeader: "Bildgröße",
            imageHeight: "Höhe",
            imageWidth: "Breite",
            textPlaceholder: "Text eingeben",
            inserttablebtn: "Tabelle einfügen",
            tabledialogHeader: "Tabelle einfügen",
            tableWidth: "Breite",
            cellpadding: "Zellauffüllung",
            cellspacing: "Zellabstand",
            columns: "Anzahl der Spalten",
            rows: "Reihenanzahl",
            tableRows: "Tabellenzeilen",
            tableColumns: "Tabellenspalten",
            tableCellHorizontalAlign: "Horizontale Ausrichtung der Tabellenzelle",
            tableCellVerticalAlign: "Vertikale Ausrichtung der Tabellenzelle",
            createTable: "Tabelle erstellen",
            removeTable: "Tabelle entfernen",
            tableHeader: "Tabellenkopfzeile",
            tableRemove: "Tabelle entfernen",
            tableCellBackground: "Tabellenzellenhintergrund",
            tableEditProperties: "Eigenschaften der Tabellenbearbeitung",
            styles: "Styles",
            insertColumnLeft: "Spalte links einfügen",
            insertColumnRight: "Spalte rechts einfügen",
            deleteColumn: "Spalte löschen",
            insertRowBefore: "Zeile vor einfügen",
            insertRowAfter: "Zeile einfügen nach",
            deleteRow: "Zeile löschen",
            tableEditHeader: "Tabelle bearbeiten",
            TableHeadingText: "Überschrift",
            TableColText: "Col",
            imageInsertLinkHeader: "Link einfügen",
            editImageHeader: "Bild bearbeiten",
            alignmentsDropDownLeft: "Linksbündig",
            alignmentsDropDownCenter: "Im Zentrum anordnen",
            alignmentsDropDownRight: "Rechts ausrichten",
            alignmentsDropDownJustify: "Justize ausrichten",
            imageDisplayDropDownInline: "In der Reihe",
            imageDisplayDropDownBreak: "Brechen",
            tableInsertRowDropDownBefore: "Reihe vorher einfügen",
            tableInsertRowDropDownAfter: "Zeile danach einfügen",
            tableInsertRowDropDownDelete: "Zeile löschen",
            tableInsertColumnDropDownLeft: "Spalte links einfügen",
            tableInsertColumnDropDownRight: "Spalte rechts einfügen",
            tableInsertColumnDropDownDelete: "Spalte löschen",
            tableVerticalAlignDropDownTop: "Top ausrichten",
            tableVerticalAlignDropDownMiddle: "Mitte ausrichten",
            tableVerticalAlignDropDownBottom: "Unten ausrichten",
            tableStylesDropDownDashedBorder: "Gestrichelte Grenzen",
            tableStylesDropDownAlternateRows: "Alternative Zeilen",
            formatsDropDownParagraph: "Absatz",
            formatsDropDownCode: "Kodex",
            formatsDropDownQuotation: "Zitat",
            formatsDropDownHeading1: "Überschrift 1",
            formatsDropDownHeading2: "Überschrift 2",
            formatsDropDownHeading3: "Überschrift 3",
            formatsDropDownHeading4: "Überschrift 4",
            fontNameSegoeUI: "Segoe UI",
            fontNameArial: "Arial",
            fontNameGeorgia: "Georgia",
            fontNameImpact: "Einschlag",
            fontNameTahoma: "Tahoma",
            fontNameTimesNewRoman: "Mal Neu römisch",
            fontNameVerdana: "Verdana"
           }
       }
});

import { Component } from '@angular/core';
    import { ToolbarService, LinkService, ImageService, HtmlEditorService } from '@syncfusion/ej2-angular-richtexteditor';
    @Component({
        selector: 'app-root',
        template: `<ejs-richtexteditor id='defaultRTE' locale = 'de-DE'></ejs-richtexteditor>`,
        providers: [ToolbarService, LinkService, ImageService, HtmlEditorService]
    })
    export class AppComponent  {
    }



