export const customerData: Object[] = [
    {
      CustomerID: 'ALFKI',
      ContactName: 'Maria ',
      CompanyName: 'Alfreds Futterkiste',
      Address: 'Obere Str. 57',
      Country: 'Germany',
    },
  
    {
      CustomerID: 'ANATR',
      ContactName: 'Ana Trujillo',
      CompanyName: 'Ana Trujillo Emparedados y helados',
      Address: 'Avda. de la Constitución 2222',
      Country: 'Mexico',
    },
  
    {
      CustomerID: 'ANTON',
      ContactName: 'Antonio Moreno',
      CompanyName: 'Antonio Moreno Taquería',
      Address: 'Mataderos  2312',
      Country: 'Mexico',
    },
  
    {
      CustomerID: 'AROUT',
      ContactName: 'Thomas Hardy',
      CompanyName: 'Around the Horn',
      Address: '120 Hanover Sq.',
      Country: 'UK',
    },
  
    {
      CustomerID: 'BERGS',
      ContactName: 'Christina Berglund',
      CompanyName: 'Berglunds snabbköp',
      Address: 'Berguvsvägen  8',
      Country: 'Sweden',
    },
  
    {
      CustomerID: 'BLAUS',
      ContactName: 'Hanna Moos',
      CompanyName: 'Blauer See Delikatessen',
      Address: 'Forsterstr. 57',
      Country: 'Germany',
    },
  
    {
      CustomerID: 'BLONP',
      ContactName: 'Frédérique Citeaux',
      CompanyName: 'Blondesddsl père et fils',
      Address: '24, place Kléber',
      Country: 'France',
    },
  
    {
      CustomerID: 'BOLID',
      ContactName: 'Martín Sommer',
      CompanyName: 'Bólido Comidas preparadas',
      Address: 'C/ Araquil, 67',
      Country: 'Spain',
    },
  
    {
      CustomerID: 'BONAP',
      ContactName: 'Laurence Lebihan',
      CompanyName: 'Bon app',
      Address: '12, rue des Bouchers',
      Country: 'France',
    },
  
    {
      CustomerID: 'BOTTM',
      ContactName: 'Elizabeth Lincoln',
      CompanyName: 'Bottom-Dollar Markets',
      Address: '23 Tsawassen Blvd.',
      Country: 'Canada',
    },
  
    {
      CustomerID: 'BSBEV',
      ContactName: 'Victoria Ashworth',
      CompanyName: "B's Beverages",
      Address: 'Fauntleroy Circus',
      Country: 'UK',
    },
  
    {
      CustomerID: 'CACTU',
      ContactName: 'Patricio Simpson',
      CompanyName: 'Cactus Comidas para llevar',
      Address: 'Cerrito 333',
      Country: 'Argentina',
    },
  
    {
      CustomerID: 'CENTC',
      ContactName: 'Francisco Chang',
      CompanyName: 'Centro comercial Moctezuma',
      Address: 'Sierras de Granada 9993',
      Country: 'Mexico',
    },
  
    {
      CustomerID: 'CHOPS',
      ContactName: 'Yang Wang',
      CompanyName: 'Chop-suey Chinese',
      Address: 'Hauptstr. 29',
      Country: 'Switzerland',
    },
  
    {
      CustomerID: 'COMMI',
      ContactName: 'Pedro Afonso',
      CompanyName: 'Comércio Mineiro',
      Address: 'Av. dos Lusíadas, 23',
      Country: 'Brazil',
    },
  
    {
      CustomerID: 'CONSH',
      ContactName: 'Elizabeth Brown',
      CompanyName: 'Consolidated Holdings',
      Address: 'Berkeley Gardens 12  Brewery',
      Country: 'UK',
    },
  
    {
      CustomerID: 'DRACD',
      ContactName: 'Sven Ottlieb',
      CompanyName: 'Drachenblut Delikatessen',
      Address: 'Walserweg 21',
      Country: 'Germany',
    },
  
    {
      CustomerID: 'DUMON',
      ContactName: 'Janine Labrune',
      CompanyName: 'Du monde entier',
      Address: '67, rue des Cinquante Otages',
      Country: 'France',
    },
  
    {
      CustomerID: 'EASTC',
      ContactName: 'Ann Devon',
      CompanyName: 'Eastern Connection',
      Address: '35 King George',
      Country: 'UK',
    },
  
    {
      CustomerID: 'ERNSH',
      ContactName: 'Roland Mendel',
      CompanyName: 'Ernst Handel',
      Address: 'Kirchgasse 6',
      Country: 'Austria',
    },
  
    {
      CustomerID: 'FAMIA',
      ContactName: 'Aria Cruz',
      CompanyName: 'Familia Arquibaldo',
      Address: 'Rua Orós, 92',
      Country: 'Brazil',
    },
  
    {
      CustomerID: 'FISSA',
      ContactName: 'Diego Roel',
      CompanyName: 'FISSA Fabrica Inter. Salchichas S.A.',
      Address: 'C/ Moralzarzal, 86',
      Country: 'Spain',
    },
  
    {
      CustomerID: 'FOLIG',
      ContactName: 'Martine Rancé',
      CompanyName: 'Folies gourmandes',
      Address: '184, chaussée de Tournai',
      Country: 'France',
    },
  
    {
      CustomerID: 'FOLKO',
      ContactName: 'Maria Larsson',
      CompanyName: 'Folk och fä HB',
      Address: 'Åkergatan 24',
      Country: 'Sweden',
    },
  
    {
      CustomerID: 'FRANK',
      ContactName: 'Peter Franken',
      CompanyName: 'Frankenversand',
      Address: 'Berliner Platz 43',
      Country: 'Germany',
    },
  
    {
      CustomerID: 'FRANR',
      ContactName: 'Carine Schmitt',
      CompanyName: 'France restauration',
      Address: '54, rue Royale',
      Country: 'France',
    },
  
    {
      CustomerID: 'FRANS',
      ContactName: 'Paolo Accorti',
      CompanyName: 'Franchi S.p.A.',
      Address: 'Via Monte Bianco 34',
      Country: 'Italy',
    },
  
    {
      CustomerID: 'FURIB',
      ContactName: 'Lino Rodriguez',
      CompanyName: 'Furia Bacalhau e Frutos do Mar',
      Address: 'Jardim das rosas n. 32',
      Country: 'Portugal',
    },
  
    {
      CustomerID: 'GALED',
      ContactName: 'Eduardo Saavedra',
      CompanyName: 'Galería del gastrónomo',
      Address: 'Rambla de Cataluña, 23',
      Country: 'Spain',
    },
  
    {
      CustomerID: 'GODOS',
      ContactName: 'José Pedro Freyre',
      CompanyName: 'Godos Cocina Típica',
      Address: 'C/ Romero, 33',
      Country: 'Spain',
    },
  
    {
      CustomerID: 'GOURL',
      ContactName: 'André Fonseca',
      CompanyName: 'Gourmet Lanchonetes',
      Address: 'Av. Brasil, 442',
      Country: 'Brazil',
    },
  
    {
      CustomerID: 'GREAL',
      ContactName: 'Howard Snyder',
      CompanyName: 'Great Lakes Food Market',
      Address: '2732 Baker Blvd.',
      Country: 'USA',
    },
  
    {
      CustomerID: 'GROSR',
      ContactName: 'Manuel Pereira',
      CompanyName: 'GROSELLA-Restaurante',
      Address: '5ª Ave. Los Palos Grandes',
      Country: 'Venezuela',
    },
  
    {
      CustomerID: 'HANAR',
      ContactName: 'Mario Pontes',
      CompanyName: 'Hanari Carnes',
      Address: 'Rua do Paço, 67',
      Country: 'Brazil',
    },
  
    {
      CustomerID: 'HILAA',
      ContactName: 'Carlos Hernández',
      CompanyName: 'HILARION-Abastos',
      Address: 'Carrera 22 con Ave. Carlos Soublette #8-35',
      Country: 'Venezuela',
    },
  
    {
      CustomerID: 'HUNGC',
      ContactName: 'Yoshi Latimer',
      CompanyName: 'Hungry Coyote Import Store',
      Address: 'City Center Plaza 516 Main St.',
      Country: 'USA',
    },
  
    {
      CustomerID: 'HUNGO',
      ContactName: 'Patricia McKenna',
      CompanyName: 'Hungry Owl All-Night Grocers',
      Address: '8 Johnstown Road',
      Country: 'Ireland',
    },
  
    {
      CustomerID: 'ISLAT',
      ContactName: 'Helen Bennett',
      CompanyName: 'Island Trading',
      Address: 'Garden House Crowther Way',
      Country: 'UK',
    },
  
    {
      CustomerID: 'KOENE',
      ContactName: 'Philip Cramer',
      CompanyName: 'Königlich Essen',
      Address: 'Maubelstr. 90',
      Country: 'Germany',
    },
  
    {
      CustomerID: 'LACOR',
      ContactName: 'Daniel Tonini',
      CompanyName: "La corne d'abondance",
      Address: "67, avenue de l'Europe",
      Country: 'France',
    },
  
    {
      CustomerID: 'LAMAI',
      ContactName: 'Annette Roulet',
      CompanyName: "La maison d'Asie",
      Address: '1 rue Alsace-Lorraine',
      Country: 'France',
    },
  
    {
      CustomerID: 'LAUGB',
      ContactName: 'Yoshi Tannamuri',
      CompanyName: 'Laughing Bacchus Wine Cellars',
      Address: '1900 Oak St.',
      Country: 'Canada',
    },
  
    {
      CustomerID: 'LAZYK',
      ContactName: 'John Steel',
      CompanyName: 'Lazy K Kountry Store',
      Address: '12 Orchestra Terrace',
      Country: 'USA',
    },
  
    {
      CustomerID: 'LEHMS',
      ContactName: 'Renate Messner',
      CompanyName: 'Lehmanns Marktstand',
      Address: 'Magazinweg 7',
      Country: 'Germany',
    },
  
    {
      CustomerID: 'LETSS',
      ContactName: 'Jaime Yorres',
      CompanyName: "Let's Stop N Shop",
      Address: '87 Polk St. Suite 5',
      Country: 'USA',
    },
  
    {
      CustomerID: 'LILAS',
      ContactName: 'Carlos González',
      CompanyName: 'LILA-Supermercado',
      Address: 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo',
      Country: 'Venezuela',
    },
  
    {
      CustomerID: 'LINOD',
      ContactName: 'Felipe Izquierdo',
      CompanyName: 'LINO-Delicateses',
      Address: 'Ave. 5 de Mayo Porlamar',
      Country: 'Venezuela',
    },
  
    {
      CustomerID: 'LONEP',
      ContactName: 'Fran Wilson',
      CompanyName: 'Lonesome Pine Restaurant',
      Address: '89 Chiaroscuro Rd.',
      Country: 'USA',
    },
  
    {
      CustomerID: 'MAGAA',
      ContactName: 'Giovanni Rovelli',
      CompanyName: 'Magazzini Alimentari Riuniti',
      Address: 'Via Ludovico il Moro 22',
      Country: 'Italy',
    },
  
    {
      CustomerID: 'MAISD',
      ContactName: 'Catherine Dewey',
      CompanyName: 'Maison Dewey',
      Address: 'Rue Joseph-Bens 532',
      Country: 'Belgium',
    },
  
    {
      CustomerID: 'MEREP',
      ContactName: 'Jean Fresnière',
      CompanyName: 'Mère Paillarde',
      Address: '43 rue St. Laurent',
      Country: 'Canada',
    },
  
    {
      CustomerID: 'MORGK',
      ContactName: 'Alexander Feuer',
      CompanyName: 'Morgenstern Gesundkost',
      Address: 'Heerstr. 22',
      Country: 'Germany',
    },
  
    {
      CustomerID: 'NORTS',
      ContactName: 'Simon Crowther',
      CompanyName: 'North/South',
      Address: 'South House 300 Queensbridge',
      Country: 'UK',
    },
  
    {
      CustomerID: 'OCEAN',
      ContactName: 'Yvonne Moncada',
      CompanyName: 'Océano Atlántico Ltda.',
      Address: 'Ing. Gustavo Moncada 8585 Piso 20-A',
      Country: 'Argentina',
    },
  
    {
      CustomerID: 'OLDWO',
      ContactName: 'Rene Phillips',
      CompanyName: 'Old World Delicatessen',
      Address: '2743 Bering St.',
      Country: 'USA',
    },
  
    {
      CustomerID: 'OTTIK',
      ContactName: 'Henriette Pfalzheim',
      CompanyName: 'Ottilies Käseladen',
      Address: 'Mehrheimerstr. 369',
      Country: 'Germany',
    },
  
    {
      CustomerID: 'PARIS',
      ContactName: 'Marie Bertrand',
      CompanyName: 'Paris spécialités',
      Address: '265, boulevard Charonne',
      Country: 'France',
    },
  
    {
      CustomerID: 'PERIC',
      ContactName: 'Guillermo Fernández',
      CompanyName: 'Pericles Comidas clásicas',
      Address: 'Calle Dr. Jorge Cash 321',
      Country: 'Mexico',
    },
  
    {
      CustomerID: 'PICCO',
      ContactName: 'Georg Pipps',
      CompanyName: 'Piccolo und mehr',
      Address: 'Geislweg 14',
      Country: 'Austria',
    },
  
    {
      CustomerID: 'PRINI',
      ContactName: 'Isabel de Castro',
      CompanyName: 'Princesa Isabel Vinhos',
      Address: 'Estrada da saúde n. 58',
      Country: 'Portugal',
    },
  
    {
      CustomerID: 'QUEDE',
      ContactName: 'Bernardo Batista',
      CompanyName: 'Que Delícia',
      Address: 'Rua da Panificadora, 12',
      Country: 'Brazil',
    },
  
    {
      CustomerID: 'QUEEN',
      ContactName: 'Lúcia Carvalho',
      CompanyName: 'Queen Cozinha',
      Address: 'Alameda dos Canàrios, 891',
      Country: 'Brazil',
    },
  
    {
      CustomerID: 'QUICK',
      ContactName: 'Horst Kloss',
      CompanyName: 'QUICK-Stop',
      Address: 'Taucherstraße 10',
      Country: 'Germany',
    },
  
    {
      CustomerID: 'RANCH',
      ContactName: 'Sergio Gutiérrez',
      CompanyName: 'Rancho grande',
      Address: 'Av. del Libertador 900',
      Country: 'Argentina',
    },
  
    {
      CustomerID: 'RATTC',
      ContactName: 'Paula Wilson',
      CompanyName: 'Rattlesnake Canyon Grocery',
      Address: '2817 Milton Dr.',
      Country: 'USA',
    },
  
    {
      CustomerID: 'REGGC',
      ContactName: 'Maurizio Moroni',
      CompanyName: 'Reggiani Caseifici',
      Address: 'Strada Provinciale 124',
      Country: 'Italy',
    },
  
    {
      CustomerID: 'RICAR',
      ContactName: 'Janete Limeira',
      CompanyName: 'Ricardo Adocicados',
      Address: 'Av. Copacabana, 267',
      Country: 'Brazil',
    },
  
    {
      CustomerID: 'RICSU',
      ContactName: 'Michael Holz',
      CompanyName: 'Richter Supermarkt',
      Address: 'Grenzacherweg 237',
      Country: 'Switzerland',
    },
  
    {
      CustomerID: 'ROMEY',
      ContactName: 'Alejandra Camino',
      CompanyName: 'Romero y tomillo',
      Address: 'Gran Vía, 1',
      Country: 'Spain',
    },
  
    {
      CustomerID: 'SANTG',
      ContactName: 'Jonas Bergulfsen',
      CompanyName: 'Santé Gourmet',
      Address: 'Erling Skakkes gate 78',
      Country: 'Norway',
    },
  
    {
      CustomerID: 'SAVEA',
      ContactName: 'Jose Pavarotti',
      CompanyName: 'Save-a-lot Markets',
      Address: '187 Suffolk Ln.',
      Country: 'USA',
    },
  
    {
      CustomerID: 'SEVES',
      ContactName: 'Hari Kumar',
      CompanyName: 'Seven Seas Imports',
      Address: '90 Wadhurst Rd.',
      Country: 'UK',
    },
  
    {
      CustomerID: 'SIMOB',
      ContactName: 'Jytte Petersen',
      CompanyName: 'Simons bistro',
      Address: 'Vinbæltet 34',
      Country: 'Denmark',
    },
  
    {
      CustomerID: 'SPECD',
      ContactName: 'Dominique Perrier',
      CompanyName: 'Spécialités du monde',
      Address: '25, rue Lauriston',
      Country: 'France',
    },
  
    {
      CustomerID: 'SPLIR',
      ContactName: 'Art Braunschweiger',
      CompanyName: 'Split Rail Beer & Ale',
      Address: 'P.O. Box 555',
      Country: 'USA',
    },
  
    {
      CustomerID: 'SUPRD',
      ContactName: 'Pascale Cartrain',
      CompanyName: 'Suprêmes délices',
      Address: 'Boulevard Tirou, 255',
      Country: 'Belgium',
    },
  
    {
      CustomerID: 'THEBI',
      ContactName: 'Liz Nixon',
      CompanyName: 'The Big Cheese',
      Address: '89 Jefferson Way Suite 2',
      Country: 'USA',
    },
  
    {
      CustomerID: 'THECR',
      ContactName: 'Liu Wong',
      CompanyName: 'The Cracker Box',
      Address: '55 Grizzly Peak Rd.',
      Country: 'USA',
    },
  
    {
      CustomerID: 'TOMSP',
      ContactName: 'Karin Josephs',
      CompanyName: 'Toms Spezialitäten',
      Address: 'Luisenstr. 48',
      Country: 'Germany',
    },
  
    {
      CustomerID: 'TORTU',
      ContactName: 'Miguel Angel Paolino',
      CompanyName: 'Tortuga Restaurante',
      Address: 'Avda. Azteca 123',
      Country: 'Mexico',
    },
  
    {
      CustomerID: 'TRADH',
      ContactName: 'Anabela Domingues',
      CompanyName: 'Tradição Hipermercados',
      Address: 'Av. Inês de Castro, 414',
      Country: 'Brazil',
    },
  
    {
      CustomerID: 'TRAIH',
      ContactName: 'Helvetius Nagy',
      CompanyName: "Trail's Head Gourmet Provisioners",
      Address: '722 DaVinci Blvd.',
      Country: 'USA',
    },
  
    {
      CustomerID: 'VAFFE',
      ContactName: 'Palle Ibsen',
      CompanyName: 'Vaffeljernet',
      Address: 'Smagsloget 45',
      Country: 'Denmark',
    },
  
    {
      CustomerID: 'VICTE',
      ContactName: 'Mary Saveley',
      CompanyName: 'Victuailles en stock',
      Address: '2, rue du Commerce',
      Country: 'France',
    },
  
    {
      CustomerID: 'VINET',
      ContactName: 'Paul Henriot',
      CompanyName: 'Vins et alcools Chevalier',
      Address: "59 rue de l'Abbaye",
      Country: 'France',
    },
  
    {
      CustomerID: 'WANDK',
      ContactName: 'Rita Müller',
      CompanyName: 'Die Wandernde Kuh',
      Address: 'Adenauerallee 900',
      Country: 'Germany',
    },
  
    {
      CustomerID: 'WARTH',
      ContactName: 'Pirkko Koskitalo',
      CompanyName: 'Wartian Herkku',
      Address: 'Torikatu 38',
      Country: 'Finland',
    },
  
    {
      CustomerID: 'WELLI',
      ContactName: 'Paula Parente',
      CompanyName: 'Wellington Importadora',
      Address: 'Rua do Mercado, 12',
      Country: 'Brazil',
    },
  
    {
      CustomerID: 'WHITC',
      ContactName: 'Karl Jablonski',
      CompanyName: 'White Clover Markets',
      Address: '305 - 14th Ave. S. Suite 3B',
      Country: 'USA',
    },
  
    {
      CustomerID: 'WILMK',
      ContactName: 'Matti Karttunen',
      CompanyName: 'Wilman Kala',
      Address: 'Keskuskatu 45',
      Country: 'Finland',
    },
  
    {
      CustomerID: 'WOLZA',
      ContactName: 'Zbyszek Piestrzeniewicz',
      CompanyName: 'Wolski  Zajazd',
      Address: 'ul. Filtrowa 68',
      Country: 'Poland',
    },
  ];
  
  let order: string = JSON.stringify([
    {
      OrderID: 10248,
      CustomerID: 'VINET',
      CustomerName: 'Maria ',
      OrderDate: '1996-07-04T00:00:00.000Z',
      ShippedDate: '1996-07-16T00:00:00.000Z',
      Freight: 32.38,
      ShipName: 'Vins et alcools Chevalier',
      ShipAddress: '59 rue de l Abbaye',
      ShipCity: 'Reims',
      ShipRegion: null,
      ShipCountry: 'France',
    },
    {
      OrderID: 10249,
      CustomerID: 'TOMSP',
      CustomerName: 'Ana Trujillo',
      OrderDate: '1996-07-05T00:00:00.000Z',
      ShippedDate: '1996-07-10T00:00:00.000Z',
      Freight: 11.61,
      ShipName: 'Toms Spezialitäten',
      ShipAddress: 'Luisenstr. 48',
      ShipCity: 'Münster',
      ShipRegion: null,
      ShipCountry: 'Germany',
    },
    {
      OrderID: 10250,
      CustomerID: 'HANAR',
      CustomerName: 'Antonio Moreno',
      OrderDate: '1996-07-08T00:00:00.000Z',
      ShippedDate: '1996-07-12T00:00:00.000Z',
      Freight: 65.83,
      ShipName: 'Hanari Carnes',
      ShipAddress: 'Rua do Paço, 67',
      ShipCity: 'Rio de Janeiro',
      ShipRegion: 'RJ',
      ShipCountry: 'Brazil',
    },
    {
      OrderID: 10251,
      CustomerID: 'VICTE',
      CustomerName: 'Thomas Hardy',
      OrderDate: '1996-07-08T00:00:00.000Z',
      ShippedDate: '1996-07-15T00:00:00.000Z',
      Freight: 41.34,
      ShipName: 'Victuailles en stock',
      ShipAddress: '2, rue du Commerce',
      ShipCity: 'Lyon',
      ShipRegion: null,
      ShipCountry: 'France',
    },
    {
      OrderID: 10252,
      CustomerID: 'SUPRD',
      CustomerName: 'Christina Berglund',
      OrderDate: '1996-07-09T00:00:00.000Z',
      ShippedDate: '1996-07-11T00:00:00.000Z',
      Freight: 51.3,
      ShipName: 'Suprêmes délices',
      ShipAddress: 'Boulevard Tirou, 255',
      ShipCity: 'Charleroi',
      ShipRegion: null,
      ShipCountry: 'Belgium',
    },
    {
      OrderID: 10253,
      CustomerID: 'HANAR',
      CustomerName: 'Hanna Moos',
      OrderDate: '1996-07-10T00:00:00.000Z',
      ShippedDate: '1996-07-16T00:00:00.000Z',
      Freight: 58.17,
      ShipName: 'Hanari Carnes',
      ShipAddress: 'Rua do Paço, 67',
      ShipCity: 'Rio de Janeiro',
      ShipRegion: 'RJ',
      ShipCountry: 'Brazil',
    },
    {
      OrderID: 10254,
      CustomerID: 'CHOPS',
      CustomerName: 'Frédérique Citeaux',
      OrderDate: '1996-07-11T00:00:00.000Z',
      ShippedDate: '1996-07-23T00:00:00.000Z',
      Freight: 22.98,
      ShipName: 'Chop-suey Chinese',
      ShipAddress: 'Hauptstr. 31',
      ShipCity: 'Bern',
      ShipRegion: null,
      ShipCountry: 'Switzerland',
    },
    {
      OrderID: 10255,
      CustomerID: 'RICSU',
      CustomerName: 'Martín Sommer',
      OrderDate: '1996-07-12T00:00:00.000Z',
      ShippedDate: '1996-07-15T00:00:00.000Z',
      Freight: 148.33,
      ShipName: 'Richter Supermarkt',
      ShipAddress: 'Starenweg 5',
      ShipCity: 'Genève',
      ShipRegion: null,
      ShipCountry: 'Switzerland',
    },
    {
      OrderID: 10256,
      CustomerID: 'WELLI',
      CustomerName: 'Laurence Lebihan',
      OrderDate: '1996-07-15T00:00:00.000Z',
      ShippedDate: '1996-07-17T00:00:00.000Z',
      Freight: 13.97,
      ShipName: 'Wellington Importadora',
      ShipAddress: 'Rua do Mercado, 12',
      ShipCity: 'Resende',
      ShipRegion: 'SP',
      ShipCountry: 'Brazil',
    },
    {
      OrderID: 10257,
      CustomerID: 'HILAA',
      CustomerName: 'Elizabeth Lincoln',
      OrderDate: '1996-07-16T00:00:00.000Z',
      ShippedDate: '1996-07-22T00:00:00.000Z',
      Freight: 81.91,
      ShipName: 'HILARION-Abastos',
      ShipAddress: 'Carrera 22 con Ave. Carlos Soublette #8-35',
      ShipCity: 'San Cristóbal',
      ShipRegion: 'Táchira',
      ShipCountry: 'Venezuela',
    },
    {
      OrderID: 10258,
      CustomerID: 'ERNSH',
      CustomerName: 'Victoria Ashworth',
      OrderDate: '1996-07-17T00:00:00.000Z',
      ShippedDate: '1996-07-23T00:00:00.000Z',
      Freight: 140.51,
      ShipName: 'Ernst Handel',
      ShipAddress: 'Kirchgasse 6',
      ShipCity: 'Graz',
      ShipRegion: null,
      ShipCountry: 'Austria',
    },
    {
      OrderID: 10259,
      CustomerID: 'CENTC',
      CustomerName: 'Patricio Simpson',
      OrderDate: '1996-07-18T00:00:00.000Z',
      ShippedDate: '1996-07-25T00:00:00.000Z',
      Freight: 3.25,
      ShipName: 'Centro comercial Moctezuma',
      ShipAddress: 'Sierras de Granada 9993',
      ShipCity: 'México D.F.',
      ShipRegion: null,
      ShipCountry: 'Mexico',
    },
    {
      OrderID: 10260,
      CustomerID: 'OTTIK',
      CustomerName: 'Francisco Chang',
      OrderDate: '1996-07-19T00:00:00.000Z',
      ShippedDate: '1996-07-29T00:00:00.000Z',
      Freight: 55.09,
      ShipName: 'Ottilies Käseladen',
      ShipAddress: 'Mehrheimerstr. 369',
      ShipCity: 'Köln',
      ShipRegion: null,
      ShipCountry: 'Germany',
    },
    {
      OrderID: 10261,
      CustomerID: 'QUEDE',
      CustomerName: 'Yang Wang',
      OrderDate: '1996-07-19T00:00:00.000Z',
      ShippedDate: '1996-07-30T00:00:00.000Z',
      Freight: 3.05,
      ShipName: 'Que Delícia',
      ShipAddress: 'Rua da Panificadora, 12',
      ShipCity: 'Rio de Janeiro',
      ShipRegion: 'RJ',
      ShipCountry: 'Brazil',
    },
    {
      OrderID: 10262,
      CustomerID: 'RATTC',
      CustomerName: 'Pedro Afonso',
      OrderDate: '1996-07-22T00:00:00.000Z',
      ShippedDate: '1996-07-25T00:00:00.000Z',
      Freight: 48.29,
      ShipName: 'Rattlesnake Canyon Grocery',
      ShipAddress: '2817 Milton Dr.',
      ShipCity: 'Albuquerque',
      ShipRegion: 'NM',
      ShipCountry: 'USA',
    },
    {
      OrderID: 10263,
      CustomerID: 'ERNSH',
      CustomerName: 'Elizabeth Brown',
      OrderDate: '1996-07-23T00:00:00.000Z',
      ShippedDate: '1996-07-31T00:00:00.000Z',
      Freight: 146.06,
      ShipName: 'Ernst Handel',
      ShipAddress: 'Kirchgasse 6',
      ShipCity: 'Graz',
      ShipRegion: null,
      ShipCountry: 'Austria',
    },
    {
      OrderID: 10264,
      CustomerID: 'FOLKO',
      CustomerName: 'Sven Ottlieb',
      OrderDate: '1996-07-24T00:00:00.000Z',
      ShippedDate: '1996-08-23T00:00:00.000Z',
      Freight: 3.67,
      ShipName: 'Folk och fä HB',
      ShipAddress: 'Åkergatan 24',
      ShipCity: 'Bräcke',
      ShipRegion: null,
      ShipCountry: 'Sweden',
    },
    {
      OrderID: 10265,
      CustomerID: 'BLONP',
      CustomerName: 'Ann Devon',
      OrderDate: '1996-07-25T00:00:00.000Z',
      ShippedDate: '1996-08-12T00:00:00.000Z',
      Freight: 55.28,
      ShipName: 'Blondel père et fils',
      ShipAddress: '24, place Kléber',
      ShipCity: 'Strasbourg',
      ShipRegion: null,
      ShipCountry: 'France',
    },
    {
      OrderID: 10266,
      CustomerID: 'WARTH',
      CustomerName: 'Roland Mendel',
      OrderDate: '1996-07-26T00:00:00.000Z',
      ShippedDate: '1996-07-31T00:00:00.000Z',
      Freight: 25.73,
      ShipName: 'Wartian Herkku',
      ShipAddress: 'Torikatu 38',
      ShipCity: 'Oulu',
      ShipRegion: null,
      ShipCountry: 'Finland',
    },
    {
      OrderID: 10267,
      CustomerID: 'FRANK',
      CustomerName: 'Aria Cruz',
      OrderDate: '1996-07-29T00:00:00.000Z',
      ShippedDate: '1996-08-06T00:00:00.000Z',
      Freight: 208.58,
      ShipName: 'Frankenversand',
      ShipAddress: 'Berliner Platz 43',
      ShipCity: 'München',
      ShipRegion: null,
      ShipCountry: 'Germany',
    },
    {
      OrderID: 10268,
      CustomerID: 'GROSR',
      CustomerName: 'Diego Roel',
      OrderDate: '1996-07-30T00:00:00.000Z',
      ShippedDate: '1996-08-02T00:00:00.000Z',
      Freight: 66.29,
      ShipName: 'GROSELLA-Restaurante',
      ShipAddress: '5ª Ave. Los Palos Grandes',
      ShipCity: 'Caracas',
      ShipRegion: 'DF',
      ShipCountry: 'Venezuela',
    },
    {
      OrderID: 10269,
      CustomerID: 'WHITC',
      CustomerName: 'Martine Rancé',
      OrderDate: '1996-07-31T00:00:00.000Z',
      ShippedDate: '1996-08-09T00:00:00.000Z',
      Freight: 4.56,
      ShipName: 'White Clover Markets',
      ShipAddress: '1029 - 12th Ave. S.',
      ShipCity: 'Seattle',
      ShipRegion: 'WA',
      ShipCountry: 'USA',
    },
    {
      OrderID: 10270,
      CustomerID: 'WARTH',
      CustomerName: 'Maria Larsson',
      OrderDate: '1996-08-01T00:00:00.000Z',
      ShippedDate: '1996-08-02T00:00:00.000Z',
      Freight: 136.54,
      ShipName: 'Wartian Herkku',
      ShipAddress: 'Torikatu 38',
      ShipCity: 'Oulu',
      ShipRegion: null,
      ShipCountry: 'Finland',
    },
    {
      OrderID: 10271,
      CustomerID: 'SPLIR',
      CustomerName: 'Peter Franken',
      OrderDate: '1996-08-01T00:00:00.000Z',
      ShippedDate: '1996-08-30T00:00:00.000Z',
      Freight: 4.54,
      ShipName: 'Split Rail Beer & Ale',
      ShipAddress: 'P.O. Box 555',
      ShipCity: 'Lander',
      ShipRegion: 'WY',
      ShipCountry: 'USA',
    },
    {
      OrderID: 10272,
      CustomerID: 'RATTC',
      CustomerName: 'Carine Schmitt',
      OrderDate: '1996-08-02T00:00:00.000Z',
      ShippedDate: '1996-08-06T00:00:00.000Z',
      Freight: 98.03,
      ShipName: 'Rattlesnake Canyon Grocery',
      ShipAddress: '2817 Milton Dr.',
      ShipCity: 'Albuquerque',
      ShipRegion: 'NM',
      ShipCountry: 'USA',
    },
    {
      OrderID: 10273,
      CustomerID: 'QUICK',
      CustomerName: 'Paolo Accorti',
      OrderDate: '1996-08-05T00:00:00.000Z',
      ShippedDate: '1996-08-12T00:00:00.000Z',
      Freight: 76.07,
      ShipName: 'QUICK-Stop',
      ShipAddress: 'Taucherstraße 10',
      ShipCity: 'Cunewalde',
      ShipRegion: null,
      ShipCountry: 'Germany',
    },
    {
      OrderID: 10274,
      CustomerID: 'VINET',
      CustomerName: 'Lino Rodriguez',
      OrderDate: '1996-08-06T00:00:00.000Z',
      ShippedDate: '1996-08-16T00:00:00.000Z',
      Freight: 6.01,
      ShipName: 'Vins et alcools Chevalier',
      ShipAddress: '59 rue de l Abbaye',
      ShipCity: 'Reims',
      ShipRegion: null,
      ShipCountry: 'France',
    },
    {
      OrderID: 10275,
      CustomerID: 'MAGAA',
      CustomerName: 'Eduardo Saavedra',
      OrderDate: '1996-08-07T00:00:00.000Z',
      ShippedDate: '1996-08-09T00:00:00.000Z',
      Freight: 26.93,
      ShipName: 'Magazzini Alimentari Riuniti',
      ShipAddress: 'Via Ludovico il Moro 22',
      ShipCity: 'Bergamo',
      ShipRegion: null,
      ShipCountry: 'Italy',
    },
    {
      OrderID: 10276,
      CustomerID: 'TORTU',
      CustomerName: 'José Pedro Freyre',
      OrderDate: '1996-08-08T00:00:00.000Z',
      ShippedDate: '1996-08-14T00:00:00.000Z',
      Freight: 13.84,
      ShipName: 'Tortuga Restaurante',
      ShipAddress: 'Avda. Azteca 123',
      ShipCity: 'México D.F.',
      ShipRegion: null,
      ShipCountry: 'Mexico',
    },
    {
      OrderID: 10277,
      CustomerID: 'MORGK',
      CustomerName: 'André Fonseca',
      OrderDate: '1996-08-09T00:00:00.000Z',
      ShippedDate: '1996-08-13T00:00:00.000Z',
      Freight: 125.77,
      ShipName: 'Morgenstern Gesundkost',
      ShipAddress: 'Heerstr. 22',
      ShipCity: 'Leipzig',
      ShipRegion: null,
      ShipCountry: 'Germany',
    },
    {
      OrderID: 10278,
      CustomerID: 'BERGS',
      CustomerName: 'Howard Snyder',
      OrderDate: '1996-08-12T00:00:00.000Z',
      ShippedDate: '1996-08-16T00:00:00.000Z',
      Freight: 92.69,
      ShipName: 'Berglunds snabbköp',
      ShipAddress: 'Berguvsvägen  8',
      ShipCity: 'Luleå',
      ShipRegion: null,
      ShipCountry: 'Sweden',
    },
    {
      OrderID: 10279,
      CustomerID: 'LEHMS',
      CustomerName: 'Manuel Pereira',
      OrderDate: '1996-08-13T00:00:00.000Z',
      ShippedDate: '1996-08-16T00:00:00.000Z',
      Freight: 25.83,
      ShipName: 'Lehmanns Marktstand',
      ShipAddress: 'Magazinweg 7',
      ShipCity: 'Frankfurt a.M.',
      ShipRegion: null,
      ShipCountry: 'Germany',
    },
    {
      OrderID: 10280,
      CustomerID: 'BERGS',
      CustomerName: 'Mario Pontes',
      OrderDate: '1996-08-14T00:00:00.000Z',
      ShippedDate: '1996-09-12T00:00:00.000Z',
      Freight: 8.98,
      ShipName: 'Berglunds snabbköp',
      ShipAddress: 'Berguvsvägen  8',
      ShipCity: 'Luleå',
      ShipRegion: null,
      ShipCountry: 'Sweden',
    },
    {
      OrderID: 10281,
      CustomerID: 'ROMEY',
      CustomerName: 'Carlos Hernández',
      OrderDate: '1996-08-14T00:00:00.000Z',
      ShippedDate: '1996-08-21T00:00:00.000Z',
      Freight: 2.94,
      ShipName: 'Romero y tomillo',
      ShipAddress: 'Gran Vía, 1',
      ShipCity: 'Madrid',
      ShipRegion: null,
      ShipCountry: 'Spain',
    },
    {
      OrderID: 10282,
      CustomerID: 'ROMEY',
      CustomerName: 'Yoshi Latimer',
      OrderDate: '1996-08-15T00:00:00.000Z',
      ShippedDate: '1996-08-21T00:00:00.000Z',
      Freight: 12.69,
      ShipName: 'Romero y tomillo',
      ShipAddress: 'Gran Vía, 1',
      ShipCity: 'Madrid',
      ShipRegion: null,
      ShipCountry: 'Spain',
    },
    {
      OrderID: 10283,
      CustomerID: 'LILAS',
      CustomerName: 'Patricia McKenna',
      OrderDate: '1996-08-16T00:00:00.000Z',
      ShippedDate: '1996-08-23T00:00:00.000Z',
      Freight: 84.81,
      ShipName: 'LILA-Supermercado',
      ShipAddress: 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo',
      ShipCity: 'Barquisimeto',
      ShipRegion: 'Lara',
      ShipCountry: 'Venezuela',
    },
    {
      OrderID: 10284,
      CustomerID: 'LEHMS',
      CustomerName: 'Helen Bennett',
      OrderDate: '1996-08-19T00:00:00.000Z',
      ShippedDate: '1996-08-27T00:00:00.000Z',
      Freight: 76.56,
      ShipName: 'Lehmanns Marktstand',
      ShipAddress: 'Magazinweg 7',
      ShipCity: 'Frankfurt a.M.',
      ShipRegion: null,
      ShipCountry: 'Germany',
    },
    {
      OrderID: 10285,
      CustomerID: 'QUICK',
      CustomerName: 'Philip Cramer',
      OrderDate: '1996-08-20T00:00:00.000Z',
      ShippedDate: '1996-08-26T00:00:00.000Z',
      Freight: 76.83,
      ShipName: 'QUICK-Stop',
      ShipAddress: 'Taucherstraße 10',
      ShipCity: 'Cunewalde',
      ShipRegion: null,
      ShipCountry: 'Germany',
    },
    {
      OrderID: 10286,
      CustomerID: 'QUICK',
      CustomerName: 'Daniel Tonini',
      OrderDate: '1996-08-21T00:00:00.000Z',
      ShippedDate: '1996-08-30T00:00:00.000Z',
      Freight: 229.24,
      ShipName: 'QUICK-Stop',
      ShipAddress: 'Taucherstraße 10',
      ShipCity: 'Cunewalde',
      ShipRegion: null,
      ShipCountry: 'Germany',
    },
    {
      OrderID: 10287,
      CustomerID: 'RICAR',
      CustomerName: 'Annette Roulet',
      OrderDate: '1996-08-22T00:00:00.000Z',
      ShippedDate: '1996-08-28T00:00:00.000Z',
      Freight: 12.76,
      ShipName: 'Ricardo Adocicados',
      ShipAddress: 'Av. Copacabana, 267',
      ShipCity: 'Rio de Janeiro',
      ShipRegion: 'RJ',
      ShipCountry: 'Brazil',
    },
    {
      OrderID: 10288,
      CustomerID: 'REGGC',
      CustomerName: 'Yoshi Tannamuri',
      OrderDate: '1996-08-23T00:00:00.000Z',
      ShippedDate: '1996-09-03T00:00:00.000Z',
      Freight: 7.45,
      ShipName: 'Reggiani Caseifici',
      ShipAddress: 'Strada Provinciale 124',
      ShipCity: 'Reggio Emilia',
      ShipRegion: null,
      ShipCountry: 'Italy',
    },
    {
      OrderID: 10289,
      CustomerID: 'BSBEV',
      CustomerName: 'John Steel',
      OrderDate: '1996-08-26T00:00:00.000Z',
      ShippedDate: '1996-08-28T00:00:00.000Z',
      Freight: 22.77,
      ShipName: 'B s Beverages',
      ShipAddress: 'Fauntleroy Circus',
      ShipCity: 'London',
      ShipRegion: null,
      ShipCountry: 'UK',
    },
    {
      OrderID: 10290,
      CustomerID: 'COMMI',
      CustomerNames: 'Renate Messner',
      OrderDate: '1996-08-27T00:00:00.000Z',
      ShippedDate: '1996-09-03T00:00:00.000Z',
      Freight: 79.7,
      ShipName: 'Comércio Mineiro',
      ShipAddress: 'Av. dos Lusíadas, 23',
      ShipCity: 'Sao Paulo',
      ShipRegion: 'SP',
      ShipCountry: 'Brazil',
    },
    {
      OrderID: 10291,
      CustomerID: 'QUEDE',
      CustomerName: 'Jaime Yorres',
      OrderDate: '1996-08-27T00:00:00.000Z',
      ShippedDate: '1996-09-04T00:00:00.000Z',
      Freight: 6.4,
      ShipName: 'Que Delícia',
      ShipAddress: 'Rua da Panificadora, 12',
      ShipCity: 'Rio de Janeiro',
      ShipRegion: 'RJ',
      ShipCountry: 'Brazil',
    },
    {
      OrderID: 10292,
      CustomerID: 'TRADH',
      CustomerName: 'Carlos González',
      OrderDate: '1996-08-28T00:00:00.000Z',
      ShippedDate: '1996-09-02T00:00:00.000Z',
      Freight: 1.35,
      ShipName: 'Tradiçao Hipermercados',
      ShipAddress: 'Av. Inês de Castro, 414',
      ShipCity: 'Sao Paulo',
      ShipRegion: 'SP',
      ShipCountry: 'Brazil',
    },
    {
      OrderID: 10293,
      CustomerID: 'TORTU',
      CustomerName: 'Felipe Izquierdo',
      OrderDate: '1996-08-29T00:00:00.000Z',
      ShippedDate: '1996-09-11T00:00:00.000Z',
      Freight: 21.18,
      ShipName: 'Tortuga Restaurante',
      ShipAddress: 'Avda. Azteca 123',
      ShipCity: 'México D.F.',
      ShipRegion: null,
      ShipCountry: 'Mexico',
    },
    {
      OrderID: 10294,
      CustomerID: 'RATTC',
      CustomerName: 'Fran Wilson',
      OrderDate: '1996-08-30T00:00:00.000Z',
      ShippedDate: '1996-09-05T00:00:00.000Z',
      Freight: 147.26,
      ShipName: 'Rattlesnake Canyon Grocery',
      ShipAddress: '2817 Milton Dr.',
      ShipCity: 'Albuquerque',
      ShipRegion: 'NM',
      ShipCountry: 'USA',
    },
    {
      OrderID: 10295,
      CustomerID: 'VINET',
      CustomerName: 'Giovanni Rovelli',
      OrderDate: '1996-09-02T00:00:00.000Z',
      ShippedDate: '1996-09-10T00:00:00.000Z',
      Freight: 1.15,
      ShipName: 'Vins et alcools Chevalier',
      ShipAddress: '59 rue de l Abbaye',
      ShipCity: 'Reims',
      ShipRegion: null,
      ShipCountry: 'France',
    },
    {
      OrderID: 10296,
      CustomerID: 'LILAS',
      CustomerName: 'Catherine Dewey',
      OrderDate: '1996-09-03T00:00:00.000Z',
      ShippedDate: '1996-09-11T00:00:00.000Z',
      Freight: 0.12,
      ShipName: 'LILA-Supermercado',
      ShipAddress: 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo',
      ShipCity: 'Barquisimeto',
      ShipRegion: 'Lara',
      ShipCountry: 'Venezuela',
    },
    {
      OrderID: 10297,
      CustomerID: 'BLONP',
      CustomerName: 'Jean Fresnière',
      OrderDate: '1996-09-04T00:00:00.000Z',
      ShippedDate: '1996-09-10T00:00:00.000Z',
      Freight: 5.74,
      ShipName: 'Blondel père et fils',
      ShipAddress: '24, place Kléber',
      ShipCity: 'Strasbourg',
      ShipRegion: null,
      ShipCountry: 'France',
    },
    {
      OrderID: 10298,
      CustomerID: 'HUNGO',
      CustomerName: 'Alexander Feuer',
      OrderDate: '1996-09-05T00:00:00.000Z',
      ShippedDate: '1996-09-11T00:00:00.000Z',
      Freight: 168.22,
      ShipName: 'Hungry Owl All-Night Grocers',
      ShipAddress: '8 Johnstown Road',
      ShipCity: 'Cork',
      ShipRegion: 'Co. Cork',
      ShipCountry: 'Ireland',
    },
    {
      OrderID: 10299,
      CustomerID: 'RICAR',
      CustomerName: 'Simon Crowther',
      OrderDate: '1996-09-06T00:00:00.000Z',
      ShippedDate: '1996-09-13T00:00:00.000Z',
      Freight: 29.76,
      ShipName: 'Ricardo Adocicados',
      ShipAddress: 'Av. Copacabana, 267',
      ShipCity: 'Rio de Janeiro',
      ShipRegion: 'RJ',
      ShipCountry: 'Brazil',
    },
    {
      OrderID: 10300,
      CustomerID: 'MAGAA',
      CustomerNames: 'Yvonne Moncada',
      OrderDate: '1996-09-09T00:00:00.000Z',
      ShippedDate: '1996-09-18T00:00:00.000Z',
      Freight: 17.68,
      ShipName: 'Magazzini Alimentari Riuniti',
      ShipAddress: 'Via Ludovico il Moro 22',
      ShipCity: 'Bergamo',
      ShipRegion: null,
      ShipCountry: 'Italy',
    },
    {
      OrderID: 10301,
      CustomerID: 'WANDK',
      CustomerName: 'Rene Phillips',
      OrderDate: '1996-09-09T00:00:00.000Z',
      ShippedDate: '1996-09-17T00:00:00.000Z',
      Freight: 45.08,
      ShipName: 'Die Wandernde Kuh',
      ShipAddress: 'Adenauerallee 900',
      ShipCity: 'Stuttgart',
      ShipRegion: null,
      ShipCountry: 'Germany',
    },
    {
      OrderID: 10302,
      CustomerID: 'SUPRD',
      CustomerName: 'Pirkko Koskitalo',
      OrderDate: '1996-09-10T00:00:00.000Z',
      ShippedDate: '1996-10-09T00:00:00.000Z',
      Freight: 6.27,
      ShipName: 'Suprêmes délices',
      ShipAddress: 'Boulevard Tirou, 255',
      ShipCity: 'Charleroi',
      ShipRegion: null,
      ShipCountry: 'Belgium',
    },
    {
      OrderID: 10303,
      CustomerID: 'GODOS',
      CustomerName: 'Paula Parente',
      OrderDate: '1996-09-11T00:00:00.000Z',
      ShippedDate: '1996-09-18T00:00:00.000Z',
      Freight: 107.83,
      ShipName: 'Godos Cocina Típica',
      ShipAddress: 'C/ Romero, 33',
      ShipCity: 'Sevilla',
      ShipRegion: null,
      ShipCountry: 'Spain',
    },
    {
      OrderID: 10304,
      CustomerID: 'TORTU',
      CustomerName: 'Karl Jablonski',
      OrderDate: '1996-09-12T00:00:00.000Z',
      ShippedDate: '1996-09-17T00:00:00.000Z',
      Freight: 63.79,
      ShipName: 'Tortuga Restaurante',
      ShipAddress: 'Avda. Azteca 123',
      ShipCity: 'México D.F.',
      ShipRegion: null,
      ShipCountry: 'Mexico',
    },
    {
      OrderID: 10305,
      CustomerID: 'OLDWO',
      CustomerName: 'Matti Karttunen',
      OrderDate: '1996-09-13T00:00:00.000Z',
      ShippedDate: '1996-10-09T00:00:00.000Z',
      Freight: 257.62,
      ShipName: 'Old World Delicatessen',
      ShipAddress: '2743 Bering St.',
      ShipCity: 'Anchorage',
      ShipRegion: 'AK',
      ShipCountry: 'USA',
    },
    {
      OrderID: 10306,
      CustomerID: 'ROMEY',
      CustomerName: 'Zbyszek Piestrzeniewicz',
      OrderDate: '1996-09-16T00:00:00.000Z',
      ShippedDate: '1996-09-23T00:00:00.000Z',
      Freight: 7.56,
      ShipName: 'Romero y tomillo',
      ShipAddress: 'Gran Vía, 1',
      ShipCity: 'Madrid',
      ShipRegion: null,
      ShipCountry: 'Spain',
    },
    {
      OrderID: 10307,
      CustomerID: 'LONEP',
      CustomerName: 'Zbyszek Piestrzeniewicz',
      OrderDate: '1996-09-17T00:00:00.000Z',
      ShippedDate: '1996-09-25T00:00:00.000Z',
      Freight: 0.56,
      ShipName: 'Lonesome Pine Restaurant',
      ShipAddress: '89 Chiaroscuro Rd.',
      ShipCity: 'Portland',
      ShipRegion: 'OR',
      ShipCountry: 'USA',
    },
  ]);
  export const orderDetails: Object[] = JSON.parse(
    order,
    (field: string, value: any) => {
      let dupValue: any = value;
      if (
        typeof value === 'string' &&
        /^(\d{4}\-\d\d\-\d\d([tT][\d:\.]*){1})([zZ]|([+\-])(\d\d):?(\d\d))?$/.test(
          value
        )
      ) {
        let arr: any = dupValue.split(/[^0-9]/);
        let a: any = parseInt(arr[0], 10);
        let b: any = parseInt(arr[1], 10) - 1;
        let c: any = parseInt(arr[2], 10);
        let d: any = parseInt(arr[3], 10);
        value = new Date(a, b, c, d, parseInt(arr[4], 10), parseInt(arr[5], 10));
      }
      return value;
    }
  );
  