export let rowSpanData: object[] = [
  {
    activityName: "Tower",
    levelId: "L1-001",
    startDate: "2025-07-01",
    endDate: "2025-12-29",
    supervisor: "John Carter",
    team: "Executive Oversight",
    status: "Active",
    progress: 70,
    totalBudget: 1500000,
    paidToDate: 1050000,
    currency: "USD",
    costCode: "01-00-00",
    permitStatus: "Approved",
    inspectionDate: "2025-12-30",
    inspectionStatus: "Active",
    followUpActions: "Monitor progress",
    inspectionCost: 600,
    punchListStatus: "Open",
    documentReference: "DOC-TWR-OVR",
    materialUsed: "Project Planning Kits",
    materialCost: 75000,
    materialStockRemaining: "N/A",
    children: [
      {
        activityName: "Design Stage",
        levelId: "L2-001",
        startDate: "2025-07-01",
        endDate: "2025-08-15",
        supervisor: "Ethan Park",
        team: "Design Division",
        status: "Completed",
        progress: 100,
        totalBudget: 305000,
        paidToDate: 350000,
        currency: "USD",
        costCode: "02-01-00",
        permitStatus: "Issued",
        inspectionDate: "2025-08-16",
        inspectionStatus: "Passed",
        followUpActions: "None",
        inspectionCost: 200,
        punchListStatus: "Cleared",
        documentReference: "DOC-TWR-DES-STG",
        materialUsed: "Design Blueprints",
        materialCost: 50000,
        materialStockRemaining: "N/A",
        children: [
          {
            activityName: "Architectural Design Task",
            levelId: "L3-001",
            startDate: "2025-07-02",
            endDate: "2025-07-10",
            inspectionDate: "2025-07-11",
            status: "Scheduled",
            progress: 100,
            totalBudget: 100000,
            paidToDate: 0,
            supervisor: "David Lin",
            team: "Architecture Unit",
            permitStatus: "Scheduled",
            inspectionStatus: "Passed",
            followUpActions: "None",
            inspectionCost: 100,
            punchListStatus: "Cleared",
            documentReference: "DOC-TWR-ARC-TSK",
            materialUsed: "CAD Drawings",
            materialCost: 15000,
            materialStockRemaining: "N/A",
          },
          {
            activityName: "Structural Design Task",
            levelId: "L3-002",
            startDate: "2025-07-11",
            endDate: "2025-07-25",
            inspectionDate: "2025-07-26",
            status: "Scheduled",
            progress: 100,
            totalBudget: 120000,
            paidToDate: 0,
            supervisor: "Sarah Patel",
            team: "Structural Unit",
            permitStatus: "Scheduled",
            inspectionStatus: "Passed",
            followUpActions: "None",
            inspectionCost: 100,
            punchListStatus: "Cleared",
            documentReference: "DOC-TWR-STR-TSK",
            materialUsed: "Structural Plans",
            materialCost: 15000,
            materialStockRemaining: "N/A",
          },
          {
            activityName: "MEP Design Task",
            levelId: "L3-003",
            startDate: "2025-07-26",
            endDate: "2025-08-15",
            inspectionDate: "2025-08-16",
            status: "Scheduled",
            progress: 100,
            totalBudget: 100000,
            paidToDate: 0,
            supervisor: "Carlos Rivera",
            team: "MEP Unit",
            permitStatus: "Scheduled",
            inspectionStatus: "Passed",
            followUpActions: "None",
            inspectionCost: 100,
            punchListStatus: "Cleared",
            documentReference: "DOC-TWR-MEP-TSK",
            materialUsed: "Electrical Schematics",
            materialCost: 20000,
            materialStockRemaining: "N/A",
          },
        ],
      },
      {
        activityName: "Construction Stage",
        levelId: "L2-002",
        startDate: "2025-08-16",
        endDate: "2025-10-20",
        supervisor: "James Patel",
        team: "Construction Division",
        status: "In Progress",
        progress: 75,
        totalBudget: 900000,
        paidToDate: 675000,
        currency: "USD",
        costCode: "03-01-00",
        permitStatus: "Issued",
        inspectionDate: "2025-10-21",
        inspectionStatus: "Passed with Notes",
        followUpActions: "Reinforce structure",
        inspectionCost: 300,
        punchListStatus: "Open",
        documentReference: "DOC-TWR-CON-STG",
        materialUsed: "Construction Materials",
        materialCost: 50000,
        materialStockRemaining: "300 tons",
        children: [
          {
            activityName: "Foundation Construction Task",
            levelId: "L3-004",
            startDate: "2025-08-16",
            endDate: "2025-08-25",
            inspectionDate: "2025-08-26",
            status: "Completed",
            progress: 100,
            totalBudget: 305000,
            paidToDate: 350000,
            supervisor: "Robert Singh",
            team: "Foundation Crew",
            permitStatus: "Approved",
            inspectionStatus: "Passed",
            followUpActions: "None",
            inspectionCost: 100,
            punchListStatus: "Cleared",
            documentReference: "DOC-TWR-FND-TSK",
            materialUsed: "Concrete",
            materialCost: 15000,
            materialStockRemaining: "N/A",
          },
          {
            activityName: "Structural Construction Task",
            levelId: "L3-005",
            startDate: "2025-08-26",
            endDate: "2025-09-20",
            inspectionDate: "2025-09-21",
            status: "In Progress",
            progress: 80,
            totalBudget: 300000,
            paidToDate: 240000,
            supervisor: "Nathan Blake",
            team: "Structural Team",
            permitStatus: "Approved",
            inspectionStatus: "Passed with Notes",
            followUpActions: "Reinforce beams",
            inspectionCost: 100,
            punchListStatus: "Open",
            documentReference: "DOC-TWR-STR-TSK",
            materialUsed: "Steel Beams",
            materialCost: 20000,
            materialStockRemaining: "200 tons",
          },
          {
            activityName: "Exterior Construction Task",
            levelId: "L3-006",
            startDate: "2025-09-21",
            endDate: "2025-10-20",
            inspectionDate: "2025-10-21",
            status: "In Progress",
            progress: 40,
            totalBudget: 300000,
            paidToDate: 120000,
            supervisor: "Thomas Reed",
            team: "Exterior Crew",
            permitStatus: "Approved",
            inspectionStatus: "Passed with Notes",
            followUpActions: "Continue exterior work",
            inspectionCost: 100,
            punchListStatus: "Open",
            documentReference: "DOC-TWR-EXT-TSK",
            materialUsed: "Metal Panels",
            materialCost: 15000,
            materialStockRemaining: "300 panels",
          },
        ],
      },
      {
        activityName: "Safety Stage",
        levelId: "L2-003",
        startDate: "2025-10-21",
        endDate: "2025-11-05",
        supervisor: "Nathan Blake",
        team: "Safety Division",
        status: "In Progress",
        progress: 60,
        totalBudget: 50000,
        paidToDate: 30000,
        currency: "USD",
        costCode: "04-01-00",
        permitStatus: "Issued",
        inspectionDate: "2025-11-06",
        inspectionStatus: "Scheduled",
        followUpActions: "Complete safety audit",
        inspectionCost: 0,
        punchListStatus: "Open",
        documentReference: "DOC-TWR-SAF-STG",
        materialUsed: "Safety Equipment",
        materialCost: 10000,
        materialStockRemaining: "50 units",
        children: [
          {
            activityName: "OSHA Compliance Task",
            levelId: "L3-007",
            startDate: "2025-10-21",
            endDate: "2025-10-27",
            inspectionDate: "2025-10-28",
            status: "In Progress",
            progress: 70,
            totalBudget: 20000,
            paidToDate: 14000,
            supervisor: "Laura Bennett",
            team: "Safety Inspectors",
            permitStatus: "Issued",
            inspectionStatus: "In Progress",
            followUpActions: "Complete briefing",
            inspectionCost: 0,
            punchListStatus: "Open",
            documentReference: "DOC-TWR-OSHA-TSK",
            materialUsed: "Safety Gear",
            materialCost: 4000,
            materialStockRemaining: "40 helmets",
          },
          {
            activityName: "Fire Safety Task",
            levelId: "L3-008",
            startDate: "2025-10-28",
            endDate: "2025-11-01",
            inspectionDate: "2025-11-02",
            status: "Scheduled",
            progress: 30,
            totalBudget: 15000,
            paidToDate: 0,
            supervisor: "Melissa Tran",
            team: "Fire Safety Team",
            permitStatus: "Issued",
            inspectionStatus: "Scheduled",
            followUpActions: "Install exits",
            inspectionCost: 0,
            punchListStatus: "Open",
            documentReference: "DOC-TWR-FIRE-TSK",
            materialUsed: "Extinguishers",
            materialCost: 3000,
            materialStockRemaining: "15 units",
          },
          {
            activityName: "Structural Audit Task",
            levelId: "L3-009",
            startDate: "2025-11-02",
            endDate: "2025-11-05",
            inspectionDate: "2025-11-06",
            status: "Scheduled",
            progress: 20,
            totalBudget: 15000,
            paidToDate: 0,
            supervisor: "David Lin",
            team: "Audit Engineers",
            permitStatus: "Issued",
            inspectionStatus: "Scheduled",
            followUpActions: "Verify integrity",
            inspectionCost: 0,
            punchListStatus: "Open",
            documentReference: "DOC-TWR-AUD-TSK",
            materialUsed: "Inspection Tools",
            materialCost: 3000,
            materialStockRemaining: "N/A",
          },
        ],
      },
      {
        activityName: "Finishing Stage",
        levelId: "L2-004",
        startDate: "2025-11-06",
        endDate: "2025-12-10",
        supervisor: "Melissa Tran",
        team: "Finishing Division",
        status: "Planning",
        progress: 30,
        totalBudget: 250000,
        paidToDate: 75000,
        currency: "USD",
        costCode: "05-01-00",
        permitStatus: "Under Review",
        inspectionDate: "2025-12-11",
        inspectionStatus: "Scheduled",
        followUpActions: "Begin interior work",
        inspectionCost: 0,
        punchListStatus: "Pending",
        documentReference: "DOC-TWR-FIN-STG",
        materialUsed: "Finishing Supplies",
        materialCost: 25000,
        materialStockRemaining: "200 units",
        children: [
          {
            activityName: "Interior Drywall Task",
            levelId: "L3-010",
            startDate: "2025-11-06",
            endDate: "2025-11-20",
            inspectionDate: "2025-11-21",
            status: "In Progress",
            progress: 50,
            totalBudget: 80000,
            paidToDate: 40000,
            supervisor: "Hannah Kim",
            team: "Drywall Crew",
            permitStatus: "Issued",
            inspectionStatus: "In Progress",
            followUpActions: "Check alignment",
            inspectionCost: 0,
            punchListStatus: "Open",
            documentReference: "DOC-TWR-DRY-TSK",
            materialUsed: "Drywall Sheets",
            materialCost: 8000,
            materialStockRemaining: "150 panels",
          },
          {
            activityName: "Flooring Installation Task",
            levelId: "L3-011",
            startDate: "2025-11-21",
            endDate: "2025-12-01",
            inspectionDate: "2025-12-02",
            status: "Scheduled",
            progress: 10,
            totalBudget: 80000,
            paidToDate: 0,
            supervisor: "Sarah Patel",
            team: "Flooring Team",
            permitStatus: "Issued",
            inspectionStatus: "Scheduled",
            followUpActions: "Verify level",
            inspectionCost: 0,
            punchListStatus: "Open",
            documentReference: "DOC-TWR-FLR-TSM",
            materialUsed: "Concrete Flooring",
            materialCost: 10000,
            materialStockRemaining: "200 bags",
          },
          {
            activityName: "Fixture Setup Task",
            levelId: "L3-012",
            startDate: "2025-12-02",
            endDate: "2025-12-10",
            inspectionDate: "2025-12-11",
            status: "Scheduled",
            progress: 10,
            totalBudget: 90000,
            paidToDate: 0,
            supervisor: "Lucas Nguyen",
            team: "Fit-Out Crew",
            permitStatus: "Issued",
            inspectionStatus: "Scheduled",
            followUpActions: "Install fixtures",
            inspectionCost: 0,
            punchListStatus: "Open",
            documentReference: "DOC-TWR-FIX-TSK",
            materialUsed: "Lighting Fixtures",
            materialCost: 7000,
            materialStockRemaining: "50 units",
          },
        ],
      },
      {
        activityName: "Closeout Stage",
        levelId: "L2-005",
        startDate: "2025-12-11",
        endDate: "2025-12-29",
        supervisor: "Emma Wilson",
        team: "Closeout Division",
        status: "Planning",
        progress: 20,
        totalBudget: 50000,
        paidToDate: 10000,
        currency: "USD",
        costCode: "06-01-00",
        permitStatus: "Under Review",
        inspectionDate: "2025-12-30",
        inspectionStatus: "Scheduled",
        followUpActions: "Finalize handover",
        inspectionCost: 0,
        punchListStatus: "Open",
        documentReference: "DOC-TWR-CLO-STG",
        materialUsed: "Closeout Documents",
        materialCost: 5000,
        materialStockRemaining: "N/A",
        children: [
          {
            activityName: "Punch List Review Task",
            levelId: "L3-013",
            startDate: "2025-12-11",
            endDate: "2025-12-15",
            inspectionDate: "2025-12-16",
            status: "Scheduled",
            progress: 20,
            totalBudget: 15000,
            paidToDate: 0,
            supervisor: "John Carter",
            team: "Closeout Team",
            permitStatus: "Scheduled",
            inspectionStatus: "Not Started",
            followUpActions: "Resolve issues",
            inspectionCost: 0,
            punchListStatus: "Pending",
            documentReference: "DOC-TWR-PLR-TSK",
            materialUsed: "Punch List Forms",
            materialCost: 2000,
            materialStockRemaining: "N/A",
          },
          {
            activityName: "Final Documentation Task",
            levelId: "L3-014",
            startDate: "2025-12-16",
            endDate: "2025-12-22",
            inspectionDate: "2025-12-23",
            status: "Scheduled",
            progress: 20,
            totalBudget: 15000,
            paidToDate: 0,
            supervisor: "Emily Foster",
            team: "Documentation Team",
            permitStatus: "Scheduled",
            inspectionStatus: "Not Started",
            followUpActions: "Prepare reports",
            inspectionCost: 0,
            punchListStatus: "Pending",
            documentReference: "DOC-TWR-FD-TSK",
            materialUsed: "As-Built Drawings",
            materialCost: 2000,
            materialStockRemaining: "N/A",
          },
          {
            activityName: "Client Handover Task",
            levelId: "L3-015",
            startDate: "2025-12-23",
            endDate: "2025-12-29",
            inspectionDate: "2025-12-30",
            status: "Scheduled",
            progress: 20,
            totalBudget: 20000,
            paidToDate: 0,
            supervisor: "Emma Wilson",
            team: "Client Relations",
            permitStatus: "Scheduled",
            inspectionStatus: "Not Started",
            followUpActions: "Conduct walkthrough",
            inspectionCost: 0,
            punchListStatus: "Pending",
            documentReference: "DOC-TWR-CH-TSK",
            materialUsed: "Handover Kits",
            materialCost: 1000,
            materialStockRemaining: "Delivered",
          },
        ],
      },
    ],
  },
  {
    activityName: "Warehouse",
    levelId: "L1-004",
    startDate: "2025-08-01",
    endDate: "2025-12-28",
    supervisor: "Emma Wilson",
    team: "Executive Oversight",
    status: "Active",
    progress: 55,
    totalBudget: 1030000,
    paidToDate: 566500,
    currency: "USD",
    costCode: "01-00-00",
    permitStatus: "Approved",
    inspectionDate: "2025-12-29",
    inspectionStatus: "Passed with Notes",
    followUpActions: "Address structural concerns",
    inspectionCost: 400,
    punchListStatus: "Open",
    documentReference: "DOC-WH-OVR",
    materialUsed: "Project Planning Kits",
    materialCost: 50000,
    materialStockRemaining: "N/A",
    children: [
      {
        activityName: "Design Stage",
        levelId: "L2-016",
        startDate: "2025-08-01",
        endDate: "2025-09-10",
        supervisor: "Ethan Park",
        team: "Design Division",
        status: "Completed",
        progress: 100,
        totalBudget: 202000,
        paidToDate: 220000,
        currency: "USD",
        costCode: "02-01-00",
        permitStatus: "Issued",
        inspectionDate: "2025-09-11",
        inspectionStatus: "Passed",
        followUpActions: "None",
        inspectionCost: 300,
        punchListStatus: "Cleared",
        documentReference: "DOC-WH-DES-STG",
        materialUsed: "Design Blueprints",
        materialCost: 30000,
        materialStockRemaining: "N/A",
        children: [
          {
            activityName: "Architectural Design Task",
            levelId: "L3-046",
            startDate: "2025-08-02",
            endDate: "2025-08-12",
            inspectionDate: "2025-08-13",
            status: "Completed",
            progress: 100,
            totalBudget: 70000,
            paidToDate: 70200,
            supervisor: "David Lin",
            team: "Architecture Unit",
            permitStatus: "Approved",
            inspectionStatus: "Passed",
            followUpActions: "None",
            inspectionCost: 100,
            punchListStatus: "Cleared",
            documentReference: "DOC-WH-ARC-TSK",
            materialUsed: "CAD Drawings",
            materialCost: 10000,
            materialStockRemaining: "N/A",
          },
          {
            activityName: "Structural Design Task",
            levelId: "L3-047",
            startDate: "2025-08-13",
            endDate: "2025-08-28",
            inspectionDate: "2025-08-29",
            status: "Completed",
            progress: 100,
            totalBudget: 72000,
            paidToDate: 70000,
            supervisor: "Sarah Patel",
            team: "Structural Unit",
            permitStatus: "Approved",
            inspectionStatus: "Passed",
            followUpActions: "None",
            inspectionCost: 100,
            punchListStatus: "Cleared",
            documentReference: "DOC-WH-STR-TSK",
            materialUsed: "Structural Plans",
            materialCost: 10000,
            materialStockRemaining: "N/A",
          },
          {
            activityName: "MEP Design Task",
            levelId: "L3-048",
            startDate: "2025-08-29",
            endDate: "2025-09-10",
            inspectionDate: "2025-09-11",
            status: "Completed",
            progress: 100,
            totalBudget: 62000,
            paidToDate: 60000,
            supervisor: "Carlos Rivera",
            team: "MEP Unit",
            permitStatus: "Approved",
            inspectionStatus: "Passed",
            followUpActions: "None",
            inspectionCost: 100,
            punchListStatus: "Cleared",
            documentReference: "DOC-WH-MEP-TSK",
            materialUsed: "Electrical Schematics",
            materialCost: 10000,
            materialStockRemaining: "N/A",
          },
        ],
      },
      {
        activityName: "Construction Stage",
        levelId: "L2-017",
        startDate: "2025-09-11",
        endDate: "2025-11-20",
        supervisor: "James Patel",
        team: "Construction Division",
        status: "In Progress",
        progress: 50,
        totalBudget: 800000,
        paidToDate: 400000,
        currency: "USD",
        costCode: "03-01-00",
        permitStatus: "Issued",
        inspectionDate: "2025-11-21",
        inspectionStatus: "Passed with Notes",
        followUpActions: "Address structural issues",
        inspectionCost: 400,
        punchListStatus: "Open",
        documentReference: "DOC-WH-CON-STG",
        materialUsed: "Construction Materials",
        materialCost: 200000,
        materialStockRemaining: "500 tons",
        children: [
          {
            activityName: "Foundation Construction Task",
            levelId: "L3-049",
            startDate: "2025-09-11",
            endDate: "2025-09-25",
            inspectionDate: "2025-09-26",
            status: "Completed",
            progress: 100,
            totalBudget: 300000,
            paidToDate: 320000,
            supervisor: "Robert Singh",
            team: "Foundation Crew",
            permitStatus: "Approved",
            inspectionStatus: "Passed",
            followUpActions: "None",
            inspectionCost: 100,
            punchListStatus: "Cleared",
            documentReference: "DOC-WH-FND-TSK",
            materialUsed: "Concrete Mix",
            materialCost: 80000,
            materialStockRemaining: "N/A",
          },
          {
            activityName: "Framing Construction Task",
            levelId: "L3-050",
            startDate: "2025-09-26",
            endDate: "2025-10-25",
            inspectionDate: "2025-10-26",
            status: "In Progress",
            progress: 60,
            totalBudget: 300000,
            paidToDate: 180000,
            supervisor: "Angela Moore",
            team: "Structural Crew",
            permitStatus: "Approved",
            inspectionStatus: "Passed with Notes",
            followUpActions: "Continue framing",
            inspectionCost: 200,
            punchListStatus: "Open",
            documentReference: "DOC-WH-FRM-TSK",
            materialUsed: "Steel Beams",
            materialCost: 60000,
            materialStockRemaining: "200 tons",
          },
          {
            activityName: "Exterior Construction Task",
            levelId: "L3-051",
            startDate: "2025-10-26",
            endDate: "2025-11-20",
            inspectionDate: "2025-11-21",
            status: "In Progress",
            progress: 20,
            totalBudget: 200000,
            paidToDate: 40000,
            supervisor: "Thomas Reed",
            team: "Exterior Crew",
            permitStatus: "Issued",
            inspectionStatus: "In Progress",
            followUpActions: "Continue exterior work",
            inspectionCost: 0,
            punchListStatus: "Open",
            documentReference: "DOC-WH-EXT-TSK",
            materialUsed: "Metal Panels",
            materialCost: 60000,
            materialStockRemaining: "300 panels",
          },
        ],
      },
      {
        activityName: "Safety Stage",
        levelId: "L2-018",
        startDate: "2025-11-21",
        endDate: "2025-12-10",
        supervisor: "Nathan Blake",
        team: "Safety Division",
        status: "Planning",
        progress: 30,
        totalBudget: 30000,
        paidToDate: 9000,
        currency: "USD",
        costCode: "04-01-00",
        permitStatus: "Under Review",
        inspectionDate: "2025-12-11",
        inspectionStatus: "Scheduled",
        followUpActions: "Schedule safety audit",
        inspectionCost: 0,
        punchListStatus: "Scheduled",
        documentReference: "DOC-WH-SAF-STG",
        materialUsed: "Safety Equipment",
        materialCost: 5000,
        materialStockRemaining: "50 units",
        children: [
          {
            activityName: "OSHA Compliance Task",
            levelId: "L3-052",
            startDate: "2025-11-21",
            endDate: "2025-11-28",
            inspectionDate: "2025-11-29",
            status: "Scheduled",
            progress: 30,
            totalBudget: 10000,
            paidToDate: 0,
            supervisor: "Laura Bennett",
            team: "Safety Inspectors",
            permitStatus: "Scheduled",
            inspectionStatus: "Not Started",
            followUpActions: "Conduct briefing",
            inspectionCost: 0,
            punchListStatus: "Not Started",
            documentReference: "DOC-WH-OSHA-TSK",
            materialUsed: "Safety Gear",
            materialCost: 2000,
            materialStockRemaining: "40 helmets",
          },
          {
            activityName: "Fire Safety Task",
            levelId: "L3-053",
            startDate: "2025-11-29",
            endDate: "2025-12-05",
            inspectionDate: "2025-12-06",
            status: "Scheduled",
            progress: 20,
            totalBudget: 10000,
            paidToDate: 0,
            supervisor: "Melissa Tran",
            team: "Fire Safety Team",
            permitStatus: "Scheduled",
            inspectionStatus: "Not Started",
            followUpActions: "Install exits",
            inspectionCost: 0,
            punchListStatus: "Not Started",
            documentReference: "DOC-WH-FIRE-TSK",
            materialUsed: "Extinguishers",
            materialCost: 1500,
            materialStockRemaining: "15 units",
          },
          {
            activityName: "Structural Audit Task",
            levelId: "L3-054",
            startDate: "2025-12-06",
            endDate: "2025-12-10",
            inspectionDate: "2025-12-11",
            status: "Scheduled",
            progress: 20,
            totalBudget: 10000,
            paidToDate: 0,
            supervisor: "David Lin",
            team: "Audit Engineers",
            permitStatus: "Scheduled",
            inspectionStatus: "Not Started",
            followUpActions: "Verify integrity",
            inspectionCost: 0,
            punchListStatus: "Not Started",
            documentReference: "DOC-WH-AUD-TSK",
            materialUsed: "Inspection Tools",
            materialCost: 1500,
            materialStockRemaining: "N/A",
          },
        ],
      },
    ],
  },
];
