export let telecastData: Object[] = [
{
    Channel: 'USA News Network',
    Genre: 'News',
    Program12AM: 'Late Night News',
    Program1AM: 'Overnight Brief',
    Program2AM: 'Overnight Brief',
    Program3AM: 'World Recap',
    Program4AM: 'Early Report',
    Program5AM: 'Morning Preview',
    Program6AM: 'Morning Dispatch',
    Program7AM: 'Daily Brief',
    Program8AM: 'National Update',
    Program9AM: 'National Update',
    Program10AM: 'Midday Report',
    Program11AM: 'Breaking Stories',
    Program12PM: 'Global Roundup',
    Program1PM: 'Current Affairs',
    Program2PM: 'News Desk',
    Program3PM: 'Afternoon Digest',
    Program4PM: 'City Beat',
    Program5PM: 'Evening News',
    Program6PM: 'Evening News',
    Program7PM: 'World Tonight',
    Program8PM: 'Prime Report',
    Program9PM: 'Nightly Brief',
    Program10PM: 'Late Edition',
    Program11PM: 'News Wrap',
},
{
    Channel: 'American News Channel',
    Genre: 'News',
    Program12AM: 'Midnight Update',
    Program1AM: 'Global Overnight',
    Program2AM: 'Global Overnight',
    Program3AM: 'News Replay',
    Program4AM: 'Dawn Dispatch',
    Program5AM: 'Business Early',
    Program6AM: 'Early Edition',
    Program7AM: 'Business Beat',
    Program8AM: 'National Update',
    Program9AM: 'National Update',
    Program10AM: 'In Focus',
    Program11AM: 'Market Pulse',
    Program12PM: 'News Today',
    Program1PM: 'World Matters',
    Program2PM: 'Regional Review',
    Program3PM: 'Evening Preview',
    Program4PM: 'Local Stories',
    Program5PM: 'Evening News',
    Program6PM: 'Evening News',
    Program7PM: 'Global Insight',
    Program8PM: 'Prime Focus',
    Program9PM: 'Night Desk',
    Program10PM: 'Late News',
    Program11PM: 'Final Report',
},
{
    Channel: 'Science Frontier TV',
    Genre: 'Science',
    Program12AM: 'Tech Rewind',
    Program1AM: 'Cosmic Replay',
    Program2AM: 'Cosmic Replay',
    Program3AM: 'Science Vault',
    Program4AM: 'Tech Bits',
    Program5AM: 'Nature Shorts',
    Program6AM: 'How It’s Built',
    Program7AM: 'Nature Unveiled',
    Program8AM: 'Tech Titans',
    Program9AM: 'Future Innovators',
    Program10AM: 'Unknown Worlds',
    Program11AM: 'Planet Secrets',
    Program12PM: 'Tomorrow’s Tech',
    Program1PM: 'Space Frontiers',
    Program2PM: 'Myth Crackers',
    Program3PM: 'Cosmic Discoveries',
    Program4PM: 'Tech Lab',
    Program5PM: 'Science Now',
    Program6PM: 'Innovate Today',
    Program7PM: 'Future Worlds',
    Program8PM: 'Star Explorers',
    Program9PM: 'Tech Deep Dive',
    Program10PM: 'Science Spotlight',
    Program11PM: 'Night Lab',
},
{
    Channel: 'Explore America',
    Genre: 'Science',
    Program12AM: 'Wild Nights',
    Program1AM: 'Explorer Vault',
    Program2AM: 'Explorer Vault',
    Program3AM: 'Hidden Gems',
    Program4AM: 'Wild Shorts',
    Program5AM: 'Nature Dawn',
    Program6AM: 'Wild Expeditions',
    Program7AM: 'American Wilderness',
    Program8AM: 'Tech Titans',
    Program9AM: 'Future Innovators',
    Program10AM: 'Hidden Histories',
    Program11AM: 'Mega Projects',
    Program12PM: 'Great Minds',
    Program1PM: 'Beyond Earth',
    Program2PM: 'Star Journey',
    Program3PM: 'Unique Planet',
    Program4PM: 'Adventure Now',
    Program5PM: 'Wild America',
    Program6PM: 'Explorer’s Log',
    Program7PM: 'Nature Quest',
    Program8PM: 'Epic Journeys',
    Program9PM: 'Lost Worlds',
    Program10PM: 'Planet Stories',
    Program11PM: 'Night Trek',
},
{
    Channel: 'Silver Screen Network',
    Genre: 'Movies',
    Program12AM: 'Movie',
    Program1AM: 'Movie',
    Program2AM: 'Movie',
    Program3AM: 'Late Classic',
    Program4AM: 'Late Classic',
    Program5AM: 'Early Feature',
    Program6AM: 'Shadow of Truth',
    Program7AM: 'Shadow of Truth',
    Program8AM: 'Shadow of Truth',
    Program9AM: 'Power Play',
    Program10AM: 'Power Play',
    Program11AM: 'Power Play',
    Program12PM: 'Power Play',
    Program1PM: 'City Vigilante',
    Program2PM: 'City Vigilante',
    Program3PM: 'City Vigilante',
    Program4PM: 'Hero Saga',
    Program5PM: 'Hero Saga',
    Program6PM: 'Prime Movie',
    Program7PM: 'Prime Movie',
    Program8PM: 'Blockbuster Night',
    Program9PM: 'Blockbuster Night',
    Program10PM: 'Late Show',
    Program11PM: 'Late Show',
},
{
    Channel: 'Sports USA',
    Genre: 'Sports',
    Program12AM: 'Sports Replay',
    Program1AM: 'Game Highlights',
    Program2AM: 'Game Highlights',
    Program3AM: 'Sports Vault',
    Program4AM: 'Early Recap',
    Program5AM: 'Morning Warmup',
    Program6AM: 'Morning Kickoff',
    Program7AM: 'Football Classics',
    Program8AM: 'Live Game Day',
    Program9AM: 'Live Game Day',
    Program10AM: 'Top Plays',
    Program11AM: 'Sports Talk',
    Program12PM: 'Hoops Highlights',
    Program1PM: 'Game Plan',
    Program2PM: 'Sports Roundup',
    Program3PM: 'NFL Breakdown',
    Program4PM: 'Sports Desk',
    Program5PM: 'Live Coverage',
    Program6PM: 'Game Night',
    Program7PM: 'Prime Sports',
    Program8PM: 'Big Match',
    Program9PM: 'Sports Wrap',
    Program10PM: 'Late Game',
    Program11PM: 'Night Recap',
},
{
    Channel: 'All Sports Network',
    Genre: 'Sports',
    Program12AM: 'Late Highlights',
    Program1AM: 'Sports Classics',
    Program2AM: 'Sports Classics',
    Program3AM: 'Game Rewind',
    Program4AM: 'Early Games',
    Program5AM: 'Sports Warmup',
    Program6AM: 'Morning Kickoff',
    Program7AM: 'Classic Matchups',
    Program8AM: 'Live Game Day',
    Program9AM: 'Live Game Day',
    Program10AM: 'Top Plays',
    Program11AM: 'Sports Talk',
    Program12PM: 'Baseball Recap',
    Program1PM: 'Game Plan',
    Program2PM: 'Sports Roundup',
    Program3PM: 'Soccer Highlights',
    Program4PM: 'Sports Central',
    Program5PM: 'Live Action',
    Program6PM: 'Prime Match',
    Program7PM: 'Sports Night',
    Program8PM: 'Big Game',
    Program9PM: 'Game Recap',
    Program10PM: 'Late Sports',
    Program11PM: 'Final Score',
},
{
    Channel: 'Kids Fun Zone',
    Genre: 'Kids',
    Program12AM: 'Cartoon Rewind',
    Program1AM: 'Late Toons',
    Program2AM: 'Late Toons',
    Program3AM: 'Kid Classics',
    Program4AM: 'Kid Classics',
    Program5AM: 'Early Toons',
    Program6AM: 'Adventure Pals',
    Program7AM: 'Super Heroes',
    Program8AM: 'Super Heroes',
    Program9AM: 'Super Heroes',
    Program10AM: 'Mystery Crew',
    Program11AM: 'Funny Chase',
    Program12PM: 'Cartoon Craze',
    Program1PM: 'Quest Buddies',
    Program2PM: 'Quest Buddies',
    Program3PM: 'Team Turbo',
    Program4PM: 'Fun Factory',
    Program5PM: 'Kid Quest',
    Program6PM: 'Toon Time',
    Program7PM: 'Family Flicks',
    Program8PM: 'Adventure Hour',
    Program9PM: 'Night Toons',
    Program10PM: 'Night Toons',
    Program11PM: 'Sleepy Stories',
},
{
    Channel: 'Family Playhouse',
    Genre: 'Kids',
    Program12AM: 'Late Kid Show',
    Program1AM: 'Moonlit Tales',
    Program2AM: 'Moonlit Tales',
    Program3AM: 'Classic Cartoons',
    Program4AM: 'Classic Cartoons',
    Program5AM: 'Morning Pals',
    Program6AM: 'Little Explorers',
    Program7AM: 'Rescue Pals',
    Program8AM: 'House of Laughs',
    Program9AM: 'House of Laughs',
    Program10AM: 'Mystery Crew',
    Program11AM: 'Magic Wishes',
    Program12PM: 'Teen Spotlight',
    Program1PM: 'Ocean Adventures',
    Program2PM: 'Ocean Adventures',
    Program3PM: 'Rescue Pals',
    Program4PM: 'Family Fun',
    Program5PM: 'Kid Adventures',
    Program6PM: 'Toon Party',
    Program7PM: 'Family Time',
    Program8PM: 'Magic Hour',
    Program9PM: 'Evening Toons',
    Program10PM: 'Evening Toons',
    Program11PM: 'Bedtime Tales',
},
{
    Channel: 'Magic Youth TV',
    Genre: 'Kids',
    Program12AM: 'Midnight Toons',
    Program1AM: 'Starlight Stories',
    Program2AM: 'Starlight Stories',
    Program3AM: 'Toon Vault',
    Program4AM: 'Toon Vault',
    Program5AM: 'Early Adventures',
    Program6AM: 'Mouse Playhouse',
    Program7AM: 'City Kids',
    Program8AM: 'Mystery Town',
    Program9AM: 'Mystery Town',
    Program10AM: 'Mystery Crew',
    Program11AM: 'Witch Cottage',
    Program12PM: 'Swamp Tales',
    Program1PM: 'Stepbrothers',
    Program2PM: 'Stepbrothers',
    Program3PM: 'City Kids',
    Program4PM: 'Youth Quest',
    Program5PM: 'Fun Tales',
    Program6PM: 'Cartoon Club',
    Program7PM: 'Kid Heroes',
    Program8PM: 'Magic Night',
    Program9PM: 'Toon Dreams',
    Program10PM: 'Toon Dreams',
    Program11PM: 'Night Stories',
},
{
    Channel: 'Wild America TV',
    Genre: 'Wildlife',
    Program12AM: 'Night Creatures',
    Program1AM: 'Wild Rewind',
    Program2AM: 'Wild Rewind',
    Program3AM: 'Animal Vault',
    Program4AM: 'Nature Clips',
    Program5AM: 'Wild Dawn',
    Program6AM: 'Nature Guide',
    Program7AM: 'Wild Trails',
    Program8AM: 'Predator Watch',
    Program9AM: 'Predator Watch',
    Program10AM: 'Ocean Titans',
    Program11AM: 'Safari Quest',
    Program12PM: 'Big Beasts',
    Program1PM: 'Night Safari',
    Program2PM: 'Night Safari',
    Program3PM: 'Nature Guide',
    Program4PM: 'Wild Tracks',
    Program5PM: 'Animal Planet',
    Program6PM: 'Safari Nights',
    Program7PM: 'Wild World',
    Program8PM: 'Beast Hunters',
    Program9PM: 'Nature Nights',
    Program10PM: 'Wild Chronicles',
    Program11PM: 'Night Beasts',
},
{
    Channel: 'Earth Discovery',
    Genre: 'Nature',
    Program12AM: 'Planet Replay',
    Program1AM: 'Earth After Dark',
    Program2AM: 'Earth After Dark',
    Program3AM: 'Nature Classics',
    Program4AM: 'Earth Early',
    Program5AM: 'Dawn Planet',
    Program6AM: 'Planet Wonders',
    Program7AM: 'Frozen Lands',
    Program8AM: 'Life on Earth',
    Program9AM: 'Life on Earth',
    Program10AM: 'Blue Seas',
    Program11AM: 'Nature Marvels',
    Program12PM: 'Earth Insights',
    Program1PM: 'Night Safari',
    Program2PM: 'Night Safari',
    Program3PM: 'Planet Wonders',
    Program4PM: 'Eco Quest',
    Program5PM: 'Nature Now',
    Program6PM: 'Planet Pulse',
    Program7PM: 'Earth Stories',
    Program8PM: 'Wild Horizons',
    Program9PM: 'Nature Deep',
    Program10PM: 'Earth Night',
    Program11PM: 'Planet Recap',
},
];