export let projectData: Object[] = [
    { TaskID: 1, TaskName: 'Parent Task 1', StartDate: new Date('02/23/2023'), Duration: 3, Priority : 'Normal',
    EndDate: new Date('02/27/2023'), Progress: '40',Approved:true , Task_FeedbackDetails:'positive',parentID: null},
    { TaskID: 2, TaskName: 'Child Task 1', StartDate: new Date('02/23/2023'), Duration: 4, Priority : 'Low',
    EndDate: new Date('02/27/2023'), Progress: '40', parentID: 1,Task_FeedbackDetails:'positive', Approved:false},
    { TaskID: 3, TaskName: 'Child Task 2', StartDate: new Date('02/23/2023'), Duration: 2, Priority : 'Normal',
    EndDate: new Date('02/27/2023'), Progress: '40', parentID: 1, Task_FeedbackDetails:'negative',Approved:true },
    { TaskID: 4, TaskName: 'Child Task 3', StartDate: new Date('02/23/2023'), Duration: 2, Priority : 'Low',
    EndDate: new Date('02/27/2023'), Progress: '40',Task_FeedbackDetails:'negative', parentID: 1 },
   
    { TaskID: 5, TaskName: 'Parent Task 2', StartDate: new Date('03/14/2023'), Duration: 6, Priority : 'Normal',
    EndDate: new Date('03/18/2023'), Progress: '40',Task_FeedbackDetails:'negative',Approved:false , parentID: null},
    { TaskID: 6, TaskName: 'Child Task 1', StartDate: new Date('03/02/2023'), Duration: 11, Priority : 'High',
    EndDate: new Date('03/06/2023'), Progress: '40', Task_FeedbackDetails:'negative',parentID: 5,Approved:false },
    { TaskID: 7, TaskName: 'Child Task 2', StartDate: new Date('03/02/2023'), Duration: 7, Priority : 'Critical',
    EndDate: new Date('03/06/2023'), Progress: '40', Task_FeedbackDetails:'positive',parentID: 5 },
    { TaskID: 8, TaskName: 'Child Task 3', StartDate: new Date('03/02/2023'), Duration: 10, Priority : 'Breaker',
    EndDate: new Date('03/06/2023'), Progress: '40', Task_FeedbackDetails:'negative',parentID: 5,Approved:true },
    { TaskID: 9, TaskName: 'Child Task 4', StartDate: new Date('03/02/2023'), Duration: 15, Priority : 'High',
    EndDate: new Date('03/06/2023'), Progress: '40', Task_FeedbackDetails:'positive',parentID: 5 ,Approved:false},
  
    { TaskID: 10, TaskName: 'Parent Task 3', StartDate: new Date('03/09/2023'), Duration: 17, Priority : 'Breaker',
    EndDate: new Date('03/13/2023'), Progress: '40',Task_FeedbackDetails:'positive',Approved:false, parentID: null },
    { TaskID: 11, TaskName: 'Child Task 1', StartDate: new Date('03/9/2023'), Duration: 0, Priority : 'Low',
    EndDate: new Date('03/13/2023'), Progress: '40',Task_FeedbackDetails:'negative', parentID: 10 ,Approved:true},
    { TaskID: 12, TaskName: 'Child Task 2', StartDate: new Date('03/9/2023'), Duration: 10, Priority : 'Breaker',
    EndDate: new Date('03/13/2023'), Progress: '40',Task_FeedbackDetails:'negative', parentID: 10 ,Approved:false},
    { TaskID: 13, TaskName: 'Child Task 3', StartDate: new Date('03/9/2023'), Duration: 11, Priority : 'Normal',
    EndDate: new Date('03/13/2023'), Progress: '40',Task_FeedbackDetails:'positive', parentID: 10,Approved:false },
    { TaskID: 14, TaskName: 'Child Task 4', StartDate: new Date('03/9/2023'), Duration: 1, Priority : 'Normal',
    EndDate: new Date('03/13/2023'), Progress: '40',Task_FeedbackDetails:'positive', parentID: 10,Approved:false },
    { TaskID: 15, TaskName: 'Child Task 5', StartDate: new Date('03/9/2023'), Duration: 14, Priority : 'Critical',
    EndDate: new Date('03/13/2023'), Progress: '40', Task_FeedbackDetails:'negative',parentID: 10 ,Approved:true}
  ];