/**
 * TreeGrid DataSource
 */
export let textdata: Object[] = [{
    'FirstName':'Robert',
    'LastName':'King',
    'Name': 'Robert King',
    'FullName': 'RobertKing',
    'Designation': 'Chief Executive Officer',
    'EmployeeID': '1',
    'EmpID': 'EMP001',
    'Address': '507 - 20th Ave. E.Apt. 2A, Seattle',
    'Contact': '2065559857',
    'Country': 'USA',
    'Image':"",
    'DOB': new Date('2/15/1963'),

    'Children': [{
        'FirstName':'David',
        'LastName':'william',
        'Name': 'David william',
        'FullName': 'DavidWilliam',
        'Designation': 'Vice President',
        'EmployeeID': '2',
        'EmpID': 'EMP004',
        'Address': '722 Moss Bay Blvd., Kirkland',
        'Country': 'USA',
        'Contact': '2065553412',
        'DOB': new Date('5/20/1971'),
        'Image':"",

    },{
            'FirstName':'Nancy',
            'LastName':'Davolio',
            'Name': 'Nancy Davolio',
            'FullName': 'NancyDavolio',
            'Designation': 'Marketing Executive',
            'EmployeeID': '3',
            'EmpID': 'EMP035',
            'Address': '4110 Old Redmond Rd., Redmond',
            'Country': 'USA',
            'Contact': '2065558122',
            'Image':"",
            'DOB': new Date('3/19/1966'),
     },
                {
                    'FirstName':'Andrew',
                    'LastName':'Fuller',
                    'Name': 'Andrew Fuller',
                    'FullName': 'AndrewFuller',
                    'Designation': 'Sales Representative',
                    'EmployeeID': '4',
                    'EmpID': 'EMP045',
                    'Address': '14 Garrett Hill, London',
                    'Country': 'UK',
                    'Contact': '7155544848',
                    'Image':"",
                    'DOB': new Date('9/20/1980')
                },
            {
                'FirstName':'Anne',
                'LastName':'Dodsworth',
                'Name': 'Anne Dodsworth',
                'FullName': 'AnneDodsworth',
                'Designation': 'Sales Representative',
                'EmployeeID': '5',
                'EmpID': 'EMP091',
                'Address': '4726 - 11th Ave. N.E., Seattle',
                'Country': 'USA',
                'Image':"",
                'Contact': '2065551189',
                'DOB': new Date('10/19/1989')
            },
            {
                'FirstName':'Michael',
                'LastName':'Suyama',
                'Name': 'Michael Suyama',
                'FullName': 'MichaelSuyama',
                'Designation': 'Sales Representative',
                'EmployeeID': '6',
                'EmpID': 'EMP110',
                'Address': 'Coventry House Miner Rd., London',
                'Country': 'UK',
                'Image':"",
                'Contact': '7145553636',
                'DOB': new Date('11/02/1987')
            },
            {
                'FirstName':'Janet',
                'LastName':'Leverling',
                'Name': 'Janet Leverling',
                'FullName': 'JanetLeverling',
                'Designation': 'Sales Coordinator',
                'EmployeeID': '7',
                'EmpID': 'EMP131',
                'Address': 'Edgeham Hollow Winchester Way, London',
                'Country': 'UK',
                'Image':"",
                'Contact': '7145553636',
                'DOB': new Date('11/06/1990')
          
        }]},
        {
            'FirstName':'Romey',
            'LastName':'Wilson',
            'Name': 'Romey Wilson',
            'FullName': 'RomeyWilson',
            'Designation': 'Sales Executive',
            'EmployeeID': '8',
            'EmpID': 'EMP039',
            'Address': '7 Houndstooth Rd., London',
            'Country': 'UK',
            'Contact': '7125553690',
            'Image':"",
            'DOB': new Date('02/02/1980'),
            'Children': [
            {
                'FirstName':'Margaret',
                'LastName':'Peacock',
                'Name': 'Margaret Peacock',
                'FullName': 'MargaretPeacock',
                'Designation': 'Sales Representative',
                'EmployeeID': '5',
                'EmpID': 'EMP213',
                'Address': '4726 - 11th Ave. N.E., California',
                'Country': 'USA',
                'Contact': '2065551989',
                'Image':"",
                'DOB': new Date('01/21/1986')
            },
            {
                'FirstName':'Laura',
                'LastName':'Callahan',
                'Name': 'Laura Callahan',
                'FullName': 'LauraCallahan',
                'Designation': 'Sales Coordinator',
                'EmployeeID': '6',
                'EmpID': 'EMP201',
                'Address': 'Coventry House Miner Rd., London',
                'Country': 'UK',
                'Image':"",
                'Contact': '7145552222',
                'DOB': new Date( '12/01/1990')
            },
            {
                'FirstName':'Steven',
                'LastName':'Buchanan',
                'Name': 'Steven Buchanan',
                'FullName': 'StevenBuchanan',
                'Designation': 'Sales Representative',
                'EmployeeID': '7',
                'EmpID': 'EMP197',
                'Address': '200 Lincoln Ave, Salinas, CA 93901',
                'Country': 'USA',
                'Image':"",
                'Contact': '1737587408',
                'DOB': new Date('03/23/1987')
            },
            {
                'FirstName':'Tedd',
                'LastName':'Lawson',
                'Name': 'Tedd Lawson',
                'FullName': 'TeddLawson',
                'Designation': 'Sales Representative',
                'EmployeeID': '8',
                'EmpID': 'EMP167',
                'Address': '200 Lincoln Ave, Salinas, CA 93901',
                'Country': 'USA',
                'Contact': '1737587368 ',
                'DOB': new Date('08/09/1989')
            },
            ]
          }];