export const productDatas: object[] = [
  {
    "ProductID": "PROD-001",
    "ProductCategory": "Electronics",
    "Revenue": 447.19,
    "Discount": 23.26,
    "TransactionDate": new Date(1735689600000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 25,
    "OrderQuantity": 4
  },
  {
    "ProductID": "PROD-002",
    "ProductCategory": "Clothing",
    "Revenue": 128.543,
    "Discount": 15.7,
    "TransactionDate": new Date(1735776000000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 60,
    "OrderQuantity": 2
  },
  {
    "ProductID": "PROD-003",
    "ProductCategory": "Books",
    "Revenue": 89.2,
    "Discount": 10.45,
    "TransactionDate": new Date(1735862400000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 85,
    "OrderQuantity": 1
  },
  {
    "ProductID": "PROD-004",
    "ProductCategory": "Garden",
    "Revenue": 675.321,
    "Discount": 27.8,
    "TransactionDate": new Date(1735948800000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 15,
    "OrderQuantity": 6
  },
  {
    "ProductID": "PROD-005",
    "ProductCategory": "Toys",
    "Revenue": 234.67,
    "Discount": 19.12,
    "TransactionDate": new Date(1736035200000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 40,
    "OrderQuantity": 3
  },
  {
    "ProductID": "PROD-006",
    "ProductCategory": "Electronics",
    "Revenue": 512.098,
    "Discount": 22.3,
    "TransactionDate": new Date(1736121600000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 20,
    "OrderQuantity": 5
  },
  {
    "ProductID": "PROD-007",
    "ProductCategory": "Clothing",
    "Revenue": 76.54,
    "Discount": 8.9,
    "TransactionDate": new Date(1736208000000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 90,
    "OrderQuantity": 1
  },
  {
    "ProductID": "PROD-008",
    "ProductCategory": "Books",
    "Revenue": 345.231,
    "Discount": 12.67,
    "TransactionDate": new Date(1736294400000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 35,
    "OrderQuantity": 4
  },
  {
    "ProductID": "PROD-009",
    "ProductCategory": "Garden",
    "Revenue": 987.45,
    "Discount": 25.4,
    "TransactionDate": new Date(1736380800000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 10,
    "OrderQuantity": 7
  },
  {
    "ProductID": "PROD-010",
    "ProductCategory": "Toys",
    "Revenue": 156.789,
    "Discount": 17.23,
    "TransactionDate": new Date(1736467200000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 55,
    "OrderQuantity": 2
  },
  {
    "ProductID": "PROD-011",
    "ProductCategory": "Electronics",
    "Revenue": 623.12,
    "Discount": 20.56,
    "TransactionDate": new Date(1736553600000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 18,
    "OrderQuantity": 6
  },
  {
    "ProductID": "PROD-012",
    "ProductCategory": "Clothing",
    "Revenue": 321.456,
    "Discount": 14.89,
    "TransactionDate": new Date(1736640000000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 45,
    "OrderQuantity": 3
  },
  {
    "ProductID": "PROD-013",
    "ProductCategory": "Books",
    "Revenue": 78.9,
    "Discount": 11.34,
    "TransactionDate": new Date(1736726400000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 80,
    "OrderQuantity": 1
  },
  {
    "ProductID": "PROD-014",
    "ProductCategory": "Garden",
    "Revenue": 456.789,
    "Discount": 28.12,
    "TransactionDate": new Date(1736812800000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 22,
    "OrderQuantity": 5
  },
  {
    "ProductID": "PROD-015",
    "ProductCategory": "Toys",
    "Revenue": 234.56,
    "Discount": 16.78,
    "TransactionDate": new Date(1736899200000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 50,
    "OrderQuantity": 3
  },
  {
    "ProductID": "PROD-016",
    "ProductCategory": "Electronics",
    "Revenue": 789.123,
    "Discount": 21.45,
    "TransactionDate": new Date(1736985600000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 15,
    "OrderQuantity": 7
  },
  {
    "ProductID": "PROD-017",
    "ProductCategory": "Clothing",
    "Revenue": 198.76,
    "Discount": 13.21,
    "TransactionDate": new Date(1737072000000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 65,
    "OrderQuantity": 2
  },
  {
    "ProductID": "PROD-018",
    "ProductCategory": "Books",
    "Revenue": 412.345,
    "Discount": 18.9,
    "TransactionDate": new Date(1737158400000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 30,
    "OrderQuantity": 4
  },
  {
    "ProductID": "PROD-019",
    "ProductCategory": "Garden",
    "Revenue": 567.89,
    "Discount": 24.67,
    "TransactionDate": new Date(1737244800000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 20,
    "OrderQuantity": 5
  },
  {
    "ProductID": "PROD-020",
    "ProductCategory": "Toys",
    "Revenue": 345.12,
    "Discount": 15.34,
    "TransactionDate": new Date(1737331200000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 45,
    "OrderQuantity": 3
  },
  {
    "ProductID": "PROD-021",
    "ProductCategory": "Electronics",
    "Revenue": 678.901,
    "Discount": 19.78,
    "TransactionDate": new Date(1737417600000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 17,
    "OrderQuantity": 6
  },
  {
    "ProductID": "PROD-022",
    "ProductCategory": "Clothing",
    "Revenue": 234.567,
    "Discount": 12.45,
    "TransactionDate": new Date(1737504000000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 55,
    "OrderQuantity": 2
  },
  {
    "ProductID": "PROD-023",
    "ProductCategory": "Books",
    "Revenue": 89.123,
    "Discount": 9.8,
    "TransactionDate": new Date(1737590400000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 75,
    "OrderQuantity": 1
  },
  {
    "ProductID": "PROD-024",
    "ProductCategory": "Garden",
    "Revenue": 456.78,
    "Discount": 26.12,
    "TransactionDate": new Date(1737676800000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 25,
    "OrderQuantity": 4
  },
  {
    "ProductID": "PROD-025",
    "ProductCategory": "Toys",
    "Revenue": 123.456,
    "Discount": 14.56,
    "TransactionDate": new Date(1737763200000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 70,
    "OrderQuantity": 2
  },
  {
    "ProductID": "PROD-026",
    "ProductCategory": "Electronics",
    "Revenue": 789.01,
    "Discount": 22.89,
    "TransactionDate": new Date(1737849600000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 12,
    "OrderQuantity": 7
  },
  {
    "ProductID": "PROD-027",
    "ProductCategory": "Clothing",
    "Revenue": 345.67,
    "Discount": 17.23,
    "TransactionDate": new Date(1737936000000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 40,
    "OrderQuantity": 3
  },
  {
    "ProductID": "PROD-028",
    "ProductCategory": "Books",
    "Revenue": 67.89,
    "Discount": 10.12,
    "TransactionDate": new Date(1738022400000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 80,
    "OrderQuantity": 1
  },
  {
    "ProductID": "PROD-029",
    "ProductCategory": "Garden",
    "Revenue": 543.21,
    "Discount": 28.45,
    "TransactionDate": new Date(1738108800000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 18,
    "OrderQuantity": 5
  },
  {
    "ProductID": "PROD-030",
    "ProductCategory": "Toys",
    "Revenue": 234.789,
    "Discount": 16.78,
    "TransactionDate": new Date(1738195200000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 50,
    "OrderQuantity": 3
  },
  {
    "ProductID": "PROD-031",
    "ProductCategory": "Electronics",
    "Revenue": 678.123,
    "Discount": 21.34,
    "TransactionDate": new Date(1738281600000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 20,
    "OrderQuantity": 6
  },
  {
    "ProductID": "PROD-032",
    "ProductCategory": "Clothing",
    "Revenue": 123.456,
    "Discount": 13.89,
    "TransactionDate": new Date(1738368000000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 65,
    "OrderQuantity": 2
  },
  {
    "ProductID": "PROD-033",
    "ProductCategory": "Books",
    "Revenue": 456.78,
    "Discount": 18.23,
    "TransactionDate": new Date(1738454400000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 30,
    "OrderQuantity": 4
  },
  {
    "ProductID": "PROD-034",
    "ProductCategory": "Garden",
    "Revenue": 789.12,
    "Discount": 25.67,
    "TransactionDate": new Date(1738540800000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 15,
    "OrderQuantity": 7
  },
  {
    "ProductID": "PROD-035",
    "ProductCategory": "Toys",
    "Revenue": 234.56,
    "Discount": 15.45,
    "TransactionDate": new Date(1738627200000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 55,
    "OrderQuantity": 3
  },
  {
    "ProductID": "PROD-036",
    "ProductCategory": "Electronics",
    "Revenue": 567.89,
    "Discount": 20.12,
    "TransactionDate": new Date(1738713600000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 25,
    "OrderQuantity": 5
  },
  {
    "ProductID": "PROD-037",
    "ProductCategory": "Clothing",
    "Revenue": 345.67,
    "Discount": 12.78,
    "TransactionDate": new Date(1738800000000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 50,
    "OrderQuantity": 3
  },
  {
    "ProductID": "PROD-038",
    "ProductCategory": "Books",
    "Revenue": 89.123,
    "Discount": 9.34,
    "TransactionDate": new Date(1738886400000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 70,
    "OrderQuantity": 1
  },
  {
    "ProductID": "PROD-039",
    "ProductCategory": "Garden",
    "Revenue": 456.789,
    "Discount": 26.89,
    "TransactionDate": new Date(1738972800000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 20,
    "OrderQuantity": 4
  },
  {
    "ProductID": "PROD-040",
    "ProductCategory": "Toys",
    "Revenue": 123.456,
    "Discount": 14.12,
    "TransactionDate": new Date(1739059200000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 60,
    "OrderQuantity": 2
  },
  {
    "ProductID": "PROD-041",
    "ProductCategory": "Electronics",
    "Revenue": 789.01,
    "Discount": 22.45,
    "TransactionDate": new Date(1739145600000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 15,
    "OrderQuantity": 7
  },
  {
    "ProductID": "PROD-042",
    "ProductCategory": "Clothing",
    "Revenue": 345.67,
    "Discount": 17.89,
    "TransactionDate": new Date(1739232000000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 45,
    "OrderQuantity": 3
  },
  {
    "ProductID": "PROD-043",
    "ProductCategory": "Books",
    "Revenue": 67.89,
    "Discount": 10.56,
    "TransactionDate": new Date(1739318400000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 75,
    "OrderQuantity": 1
  },
  {
    "ProductID": "PROD-044",
    "ProductCategory": "Garden",
    "Revenue": 543.21,
    "Discount": 28.23,
    "TransactionDate": new Date(1739404800000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 18,
    "OrderQuantity": 5
  },
  {
    "ProductID": "PROD-045",
    "ProductCategory": "Toys",
    "Revenue": 234.789,
    "Discount": 16.34,
    "TransactionDate": new Date(1739491200000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 50,
    "OrderQuantity": 3
  },
  {
    "ProductID": "PROD-046",
    "ProductCategory": "Electronics",
    "Revenue": 678.123,
    "Discount": 21.78,
    "TransactionDate": new Date(1739577600000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 20,
    "OrderQuantity": 6
  },
  {
    "ProductID": "PROD-047",
    "ProductCategory": "Clothing",
    "Revenue": 123.456,
    "Discount": 13.45,
    "TransactionDate": new Date(1739664000000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 70,
    "OrderQuantity": 2
  },
  {
    "ProductID": "PROD-048",
    "ProductCategory": "Books",
    "Revenue": 456.78,
    "Discount": 18.67,
    "TransactionDate": new Date(1739750400000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 35,
    "OrderQuantity": 4
  },
  {
    "ProductID": "PROD-049",
    "ProductCategory": "Garden",
    "Revenue": 789.12,
    "Discount": 25.12,
    "TransactionDate": new Date(1739836800000),
    "ShippingMethod": "Express",
    "WarehouseLocation": "Warehouse A",
    "StockQuantity": 15,
    "OrderQuantity": 7
  },
  {
    "ProductID": "PROD-050",
    "ProductCategory": "Toys",
    "Revenue": 234.56,
    "Discount": 15.89,
    "TransactionDate": new Date(1739923200000),
    "ShippingMethod": "Standard",
    "WarehouseLocation": "Warehouse B",
    "StockQuantity": 55,
    "OrderQuantity": 3
  }
];