export var inventoryData = [
    {
        "Inventor": "Kia Silverbrook",
        "NumberofPatentFamilies": 4737,
        "Country": "Australia",
        "Number of INPADOC patents": 9839,
        "Active": "1994-2016",
        "MainFieldsofInvention": "Printing, Digital paper, Internet, Electronics,Lab-on-a-chip, MEMS, Mechanical, VLSI",
    },
    {
        "Inventor": "Shunpei Yamazaki",
        "NumberofPatentFamilies": 4677,
        "Country": "Japan",
        "Number of INPADOC patents": "10000+",
        "Active": "1976-2016",
        "MainFieldsofInvention": "Thin film transistors, Liquid crystal displays, Solar cells, Flash memory, OLED",
    },
    {
        "Inventor": "Lowell L. Wood, Jr.",
        "NumberofPatentFamilies": 1419,
        "Country": "USA",
        "Number of INPADOC patents": 1332,
        "Active": "1977-2016",
        "MainFieldsofInvention": "Mosquito laser, Nuclear weapons",
    },
    {
        "Inventor": "Paul Lapstun",
        "NumberofPatentFamilies": 1281,
        "Country": "Australia",
        "Number of INPADOC patents": 3099,
        "Active": "2000-2016",
        "MainFieldsofInvention": "Printing, Digital paper, Internet, Electronics, CGI, VLSI",
    },
    {
        "Inventor": "Gurtej Sandhu",
        "NumberofPatentFamilies": 1255,
        "Country": "India",
        "Number of INPADOC patents": 2038,
        "Active": "1991-2016",
        "MainFieldsofInvention": "Thin film processes and materials, VLSI, Semiconductor device fabrication",
    },
    {
        "Inventor": "Jun Koyama",
        "NumberofPatentFamilies": 1240,
        "Country": "Japan",
        "Number of INPADOC patents": 4126,
        "Active": "1991-2016",
        "MainFieldsofInvention": "Thin film transistors, Liquid crystal displays, OLED",
    },
    {
        "Inventor": "Roderick A. Hyde",
        "NumberofPatentFamilies": 1240,
        "Country": "USA",
        "Number of INPADOC patents": 3360,
        "Active": "2001-2016",
        "MainFieldsofInvention": "Various",
    },
    {
        "Inventor": "Leonard Forbes",
        "NumberofPatentFamilies": 1093,
        "Country": "Canada",
        "Number of INPADOC patents": 1398,
        "Active": "1991-2016",
        "MainFieldsofInvention": "Semiconductor Memories, CCDs, Thin film processes and materials, VLSI",
    },
    {
        "Inventor": "Thomas Edison",
        "NumberofPatentFamilies": 1084,
        "Country": "USA",
        "Number of INPADOC patents": 2332,
        "Active": "1847(b)-1931(d)",
        "MainFieldsofInvention": "Electric power, Lighting, Batteries, Phonograph, Cement, Telegraphy, Mining",
    },
    {
        "Inventor": "Donald E. Weder",
        "NumberofPatentFamilies": 999,
        "Country": "USA",
        "Number of INPADOC patents": 1993,
        "Active": "1976-2015",
        "MainFieldsofInvention": "Florist supplies",
    },
    {
        "Inventor": "George Albert Lyon",
        "NumberofPatentFamilies": 993,
        "Country": "Canada",
        "Number of INPADOC patents": "NA",
        "Active": "1882(b)-1961(d)",
        "MainFieldsofInvention": "Automotive, Stainless steel products",
    },
    {
        "Inventor": "John F. O'Connor",
        "NumberofPatentFamilies": 949,
        "Country": "USA",
        "Number of INPADOC patents": "NA",
        "Active": "1864(b)-1938(d)",
        "MainFieldsofInvention": "Railway draft gearing",
    },
    {
        "Inventor": "Melvin De Groote",
        "NumberofPatentFamilies": 925,
        "Country": "USA",
        "Number of INPADOC patents": "NA",
        "Active": "1895(b)-1963(d)",
        "MainFieldsofInvention": "Chemical de-emulsifiers",
    },
    {
        "Inventor": "Jay S. Walker",
        "NumberofPatentFamilies": 918,
        "Country": "USA",
        "Number of INPADOC patents": 2206,
        "Active": "1998-2016",
        "MainFieldsofInvention": "Gaming machines",
    },
    {
        "Inventor": "Edward K. Y. Jung",
        "NumberofPatentFamilies": 911,
        "Country": "USA",
        "Number of INPADOC patents": 2254,
        "Active": "1996-2016",
        "MainFieldsofInvention": "Various",
    },
    {
        "Inventor": "Francis H. Richards",
        "NumberofPatentFamilies": 894,
        "Country": "USA",
        "Number of INPADOC patents": "NA",
        "Active": "1850(b)-19??(d)",
        "MainFieldsofInvention": "Mechanical, automation",
    }
];